(function () {
  "use strict";
  window.ELORA = window.ELORA || {};
  var otpTimer=null;
  var lastCartCount=null;
  function t(k){return window.ELORA.I18N.t(k);}function C(){return window.ELORA.Components;}
  function toast(message,icon){var root=document.getElementById("toast-root"),node=document.createElement("div");node.className="toast";node.innerHTML=C().icon(icon||"check")+'<span>'+C().escape(message)+'</span>';root.appendChild(node);if(window.lucide)window.lucide.createIcons();setTimeout(function(){node.style.opacity="0";node.style.transform="translateY(12px)";setTimeout(function(){node.remove();},300);},2600);}
  function closeOverlays(){document.body.classList.remove("is-locked");document.querySelectorAll("[data-mobile-menu],[data-filter-drawer]").forEach(function(n){n.classList.remove("is-open");});document.querySelectorAll("[data-scrim]").forEach(function(n){n.classList.remove("is-open");});var search=document.querySelector("[data-search-overlay]");if(search)search.classList.remove("is-open");document.getElementById("overlay-root").innerHTML="";}
  function openOverlay(selector){var node=document.querySelector(selector),scrim=document.querySelector("[data-scrim]");if(node)node.classList.add("is-open");if(scrim)scrim.classList.add("is-open");document.body.classList.add("is-locked");}
  function departmentChips(){return window.ELORA_DATA.categories.map(function(category){var primary='<a class="chip" href="#/shop?category='+category.id+'">'+C().escape(C().pick(category.name))+'</a>';return primary+(category.subcategories||[]).map(function(subcategory){return '<a class="chip" href="#/shop?category='+category.id+'&subcategory='+subcategory.id+'">'+C().escape(C().pick(subcategory.name))+'</a>';}).join("");}).join("");}
  function injectMobileDepartments(params){var bar=document.querySelector(".filter-bar");if(!bar||document.querySelector("[data-mobile-departments]"))return;var active=params&&params.category||"",icons={"new-in":"sparkles",fashion:"shirt","bags-shoes":"shopping-bag","accessories-beauty":"gem"},nav=document.createElement("nav");nav.className="mobile-departments";nav.setAttribute("data-mobile-departments","");nav.setAttribute("aria-label",t("shop.browseDepartments"));nav.innerHTML='<div class="mobile-departments__head"><p class="eyebrow">'+t("shop.browseDepartments")+'</p></div><div class="mobile-departments__track"><a class="mobile-department '+(!active?'is-active':'')+'" href="#/shop"><span class="mobile-department__icon">'+C().icon("layout-grid")+'</span>'+t("shop.allDepartments")+'</a>'+window.ELORA_DATA.categories.map(function(category){return '<a class="mobile-department '+(active===category.id?'is-active':'')+'" href="#/shop?category='+category.id+'" style="--department-color:'+(category.colors&&category.colors[1]||'#6f2638')+'"><span class="mobile-department__icon">'+C().icon(icons[category.id]||"tag")+'</span>'+C().escape(C().pick(category.name))+'</a>';}).join("")+'</div>';bar.parentNode.insertBefore(nav,bar);}
  function searchProducts(query){query=String(query||"").trim();if(!query)return [];var lang=window.ELORA.I18N.language, searchable=window.ELORA_DATA.products.map(function(product){var category=C().categoryById(product.category),subcategory=C().subcategoryById(product.category,product.subcategory),taxonomy=[product.category,product.subcategory,category&&category.name.en,category&&category.name.ar,subcategory&&subcategory.name.en,subcategory&&subcategory.name.ar].filter(Boolean).join(" ");return Object.assign({},product,{searchTaxonomy:taxonomy});});if(window.Fuse){var fuse=new Fuse(searchable,{keys:["name.en","name.ar","description.en","description.ar","searchTaxonomy"],threshold:.42});return fuse.search(query).map(function(x){return x.item;});}return searchable.filter(function(p){return (p.name[lang]+" "+p.description[lang]+" "+p.searchTaxonomy).toLowerCase().indexOf(query.toLowerCase())>-1;});}
  function searchRows(query){var products=searchProducts(query);if(!query){var recent=window.ELORA.store.state.searches;return '<h2>'+t("search.suggestions")+'</h2><div class="cluster" style="margin-top:1rem">'+departmentChips()+'</div>'+C().sheinCta("shein-cta--search")+(recent.length?'<h2 style="margin-top:2rem">'+t("search.recent")+'</h2><div class="cluster" style="margin-top:1rem">'+recent.map(function(q){return '<button class="chip" data-action="recent-search" data-query="'+C().escape(q)+'">'+C().escape(q)+'</button>';}).join("")+'<button class="btn btn--ghost" data-action="clear-searches">'+t("search.clear")+'</button></div>':"");}if(!products.length)return C().emptyState("search-x",t("search.noResults"),t("search.placeholder"))+C().sheinCta("shein-cta--search-empty");return '<p class="eyebrow">'+products.length+' '+t("shop.results")+'</p>'+products.slice(0,6).map(function(p){return '<a class="search-result" href="#/product/'+p.id+'"><div class="search-result__art">'+C().productImage(p,0,"search-result__image")+'</div><div><p class="eyebrow">'+C().escape(C().subcategoryLabel(p.category,p.subcategory))+'</p><h3>'+C().escape(C().pick(p.name))+'</h3><p>'+C().escape(C().pick(p.description))+'</p></div><strong>'+C().money(p.price)+'</strong></a>';}).join("");}
  function updateSearch(input,output){if(!output)return;output.innerHTML=searchRows(input.value);if(window.lucide)window.lucide.createIcons();}
  function showModal(html){var root=document.getElementById("overlay-root");root.innerHTML='<div class="scrim is-open" data-action="close-overlays"></div><div class="modal" role="dialog" aria-modal="true"><button class="icon-btn modal__close" data-action="close-overlays" aria-label="'+t("common.close")+'">'+C().icon("x")+'</button>'+html+'</div>';document.body.classList.add("is-locked");requestAnimationFrame(function(){var modal=root.querySelector(".modal");if(modal)modal.classList.add("is-open");if(window.lucide)window.lucide.createIcons();});}
  function safeMiniCartImage(value){value=String(value||"");return /^data:image\/(?:jpeg|png|webp);base64,/i.test(value)?value:"";}
  function miniCartControls(index,quantity){return '<div class="mini-cart-controls"><div class="mini-cart-qty" aria-label="'+t("cart.updateQty")+'"><button type="button" data-action="mini-cart-qty" data-index="'+index+'" data-delta="-1" aria-label="'+t("shein.decreaseQuantity")+'">−</button><span>'+Number(quantity||1)+'</span><button type="button" data-action="mini-cart-qty" data-index="'+index+'" data-delta="1" aria-label="'+t("shein.increaseQuantity")+'">+</button></div><button class="mini-cart-remove" type="button" data-action="mini-cart-remove" data-index="'+index+'" aria-label="'+t("common.remove")+'">'+C().icon("trash-2")+'</button></div>';}
  function miniCartSize(product,item,index){return '<label class="mini-cart-size"><span>'+t("product.size")+'</span><select class="select" data-mini-size data-index="'+index+'" aria-label="'+t("product.size")+'">'+product.sizes.map(function(size){var label=size==="One Size"?t("shein.oneSize"):size==="Custom / Other"?t("shein.customOther"):size;return '<option value="'+C().escape(size)+'"'+(item.size===size?' selected':"")+'>'+C().escape(label)+'</option>';}).join("")+'</select></label>';}
  function miniCartItem(item,index){
    if(item.type==="shein_request"){
      var image=safeMiniCartImage(item.image),name=C().escape(item.productName||t("shein.fallbackName"));
      return '<article class="mini-cart-item mini-cart-item--special"><div class="mini-cart-item__media">'+(image?'<img src="'+image+'" alt="'+C().escape(t("shein.previewAlt"))+'">':C().icon("image"))+'</div><div class="mini-cart-item__copy"><span class="mini-cart-item__badge">'+t("cart.specialRequest")+'</span><h3>'+name+'</h3><p>'+t("shein.color")+': '+C().escape(item.color||"—")+' · '+t("shein.size")+': '+C().escape(item.size||"—")+'</p>'+miniCartControls(index,item.quantity)+'</div><strong class="mini-cart-item__pending">'+t("shein.pricePending")+'</strong></article>';
    }
    var product=window.ELORA.store.getProduct(item.id);if(!product)return "";
    return '<article class="mini-cart-item"><div class="mini-cart-item__media">'+C().productArt(product)+'</div><div class="mini-cart-item__copy"><h3>'+C().escape(C().pick(product.name))+'</h3>'+miniCartSize(product,item,index)+miniCartControls(index,item.quantity)+'</div><strong>'+C().money(product.price*Number(item.quantity||1))+'</strong></article>';
  }
  function miniCartContent(){
    var store=window.ELORA.store,items=store.state.cart.slice(),visible=items.slice(0,4),specials=store.specialCartItems(),subtotal=store.cartSubtotal(),discount=store.state.promo?subtotal*.1:0,total=subtotal-discount;
    var body=items.length?visible.map(function(item,index){return miniCartItem(item,index);}).join("")+(items.length>visible.length?'<p class="mini-cart-more">+'+(items.length-visible.length)+' '+t("cart.moreItems")+'</p>':""):'<div class="mini-cart-empty">'+C().icon("shopping-bag")+'<p>'+t("cart.emptyMini")+'</p><a class="btn btn--secondary btn--block" href="#/shop">'+t("common.shopNow")+'</a></div>';
    var totals=items.length?'<div class="mini-cart-total"><span>'+t("cart.subtotal")+'</span><strong>'+C().money(subtotal)+'</strong></div>'+(discount?'<div class="mini-cart-discount"><span>ELORA10</span><strong>−'+C().money(discount)+'</strong></div><div class="mini-cart-total mini-cart-total--final"><span>'+t("cart.total")+'</span><strong>'+C().money(total)+'</strong></div>':"")+(specials.length?'<p class="mini-cart-note">'+t("cart.excludesSpecial")+'</p>':""):"";
    var promo=items.length?'<div class="mini-cart-promo"><input class="input" type="text" data-mini-promo value="'+C().escape(store.state.promo||"")+'" placeholder="'+t("cart.promo")+'" aria-label="'+t("cart.promo")+'"><button class="btn btn--secondary" type="button" data-action="apply-mini-promo">'+t("cart.apply")+'</button></div>':"";
    return {body:body,footer:promo+totals+'<a class="btn btn--primary btn--block" href="#/cart">'+t("cart.viewFullCart")+'</a>'};
  }
  function refreshMiniCart(){var panel=document.querySelector(".mini-cart");if(!panel)return;var content=miniCartContent(),body=panel.querySelector(".mini-cart__body"),footer=panel.querySelector(".mini-cart__footer");if(body)body.innerHTML=content.body;if(footer)footer.innerHTML=content.footer;if(window.lucide)window.lucide.createIcons();}
  function openMiniCart(){closeOverlays();var root=document.getElementById("overlay-root"),content=miniCartContent();root.innerHTML='<div class="scrim is-open" data-action="close-overlays"></div><aside class="mini-cart" role="dialog" aria-modal="true" aria-labelledby="mini-cart-title"><header class="mini-cart__head"><div><p class="eyebrow">ÉLORA</p><h2 id="mini-cart-title">'+t("cart.miniTitle")+'</h2></div><button class="icon-btn" type="button" data-action="close-overlays" aria-label="'+t("common.close")+'">'+C().icon("x")+'</button></header><div class="mini-cart__body">'+content.body+'</div><footer class="mini-cart__footer">'+content.footer+'</footer></aside>';document.body.classList.add("is-locked");requestAnimationFrame(function(){var panel=root.querySelector(".mini-cart"),close=root.querySelector('.mini-cart [data-action="close-overlays"]');if(panel)panel.classList.add("is-open");if(window.lucide)window.lucide.createIcons();if(close)close.focus();});}
  function updateCartCounters(animate){var count=window.ELORA.store.cartCount(),changed=lastCartCount!==null&&lastCartCount!==count;document.querySelectorAll("[data-cart-count]").forEach(function(node){node.textContent=count;node.hidden=!count;});if(animate&&changed)document.querySelectorAll('[data-action="open-mini-cart"]').forEach(function(button){button.classList.remove("cart-bump");void button.offsetWidth;button.classList.add("cart-bump");setTimeout(function(){button.classList.remove("cart-bump");},700);});lastCartCount=count;}
  function quickView(id){var p=window.ELORA.store.getProduct(id);if(!p)return;showModal('<div class="split"><div class="main-product-image" style="min-height:420px">'+C().productArt(p)+'</div><div class="stack"><p class="eyebrow">'+C().escape(C().categoryLabel(p.category))+' · '+C().escape(C().subcategoryLabel(p.category,p.subcategory))+'</p><h2>'+C().escape(C().pick(p.name))+'</h2><p>'+C().escape(C().pick(p.description))+'</p><strong class="price">'+C().money(p.price)+'</strong><button class="btn btn--primary" data-action="quick-add" data-id="'+p.id+'">'+t("shop.addCart")+'</button><a class="btn btn--secondary" href="#/product/'+p.id+'">'+t("common.viewDetails")+'</a></div></div>');}
  function styleQuiz(){showModal('<p class="eyebrow">'+t("home.quiz")+'</p><h2>'+t("home.quizTitle")+'</h2><p style="margin-top:1rem">'+t("home.quizBody")+'</p><div class="grid grid--3" style="margin-top:2rem">'+window.ELORA_DATA.categories.slice(0,3).map(function(cat){return '<button class="category-card" data-action="quiz-result" data-category="'+cat.id+'" style="--c1:'+cat.colors[0]+';--c2:'+cat.colors[1]+'"><h3>'+C().pick(cat.name)+'</h3></button>';}).join("")+'</div>');}
  function sizeAssistant(){showModal('<p class="eyebrow">ÉLORA FIT</p><h2>'+t("product.assistant")+'</h2><form class="stack" data-form="size" style="margin-top:2rem"><label class="field"><span>Height / الطول (cm)</span><input class="input" type="number" name="height" required min="140" max="200"></label><label class="field"><span>Preferred fit / القصة</span><select class="select"><option>Regular / عادي</option><option>Relaxed / واسع</option><option>Fitted / محدد</option></select></label><button class="btn btn--primary" type="submit">'+t("product.assistant")+'</button></form>');}
  function isSheinUrl(value){try{var url=new URL(String(value||"").trim()),labels=url.hostname.toLowerCase().split("."),index=labels.lastIndexOf("shein"),suffix=labels.slice(index+1),regional=suffix.length===2&&/^(com|co)$/.test(suffix[0])&&/^[a-z]{2}$/.test(suffix[1]),direct=suffix.length===1&&/^[a-z]{2,}$/.test(suffix[0]);return (url.protocol==="https:"||url.protocol==="http:")&&index>-1&&(direct||regional);}catch(e){return false;}}
  function validateForm(form){var valid=true;form.querySelectorAll("[required]").forEach(function(input){var ok;if(input.type==="radio"||input.type==="checkbox")ok=!!form.querySelector('input[name="'+input.name+'"]:checked');else ok=String(input.value||"").trim();if(input.type==="email"&&input.value)ok=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.value);if(input.type==="url"&&input.value)try{new URL(input.value);ok=true;}catch(e){ok=false;}if(form.getAttribute("data-form")==="shein-request"&&input.name==="productUrl")ok=isSheinUrl(input.value);input.setAttribute("aria-invalid",ok?"false":"true");var error=form.querySelector('[data-error-for="'+input.name+'"]');if(error)error.textContent=ok?"":(input.name==="productUrl"?t("shein.invalidUrl"):input.type==="email"?t("common.invalidEmail"):t("common.required"));if(!ok)valid=false;});if(!valid){var first=form.querySelector('[aria-invalid="true"]');if(first&&first.focus)first.focus();}return valid;}
  function formObject(form){var values={};new FormData(form).forEach(function(value,key){if(!(value instanceof File))values[key]=value;});return values;}
  function handleForm(form){var type=form.getAttribute("data-form");if(!validateForm(form))return;var button=form.querySelector('[type="submit"]'),values=formObject(form);if(button)window.ELORA.Animations.buttonSuccess(button);if(type==="shein-request"){var editId=form.getAttribute("data-edit-id"),request={productUrl:values.productUrl.trim(),productName:(values.productName||"").trim(),image:values.imageData||"",color:(values.color||"").trim(),size:values.size,sheinSizeText:(values.sheinSizeText||"").trim(),quantity:Math.max(1,Number(values.quantity||1)),displayedPrice:values.displayedPrice!==""&&values.displayedPrice!=null?Number(values.displayedPrice):null,displayedCurrency:values.displayedCurrency||"EGP",notes:(values.notes||"").trim()};if(editId)window.ELORA.store.updateSpecialRequest(editId,request);else window.ELORA.store.addSpecialRequest(request);document.body.classList.add("cart-bump");toast(t(editId?"shein.updated":"shein.added"),"shopping-bag");setTimeout(function(){window.ELORA.Router.navigate("/cart");},650);return;}setTimeout(function(){if(type==="login"){window.ELORA.store.setAuth(true);window.ELORA.Router.navigate("/account");}else if(type==="register"){window.ELORA.Router.navigate("/otp");}else if(type==="forgot"){window.ELORA.Router.navigate("/otp");}else if(type==="reset"){window.ELORA.Router.navigate("/reset-success");}else if(type==="checkout"){var order=window.ELORA.store.submitOrder(values);if(order)window.ELORA.Router.navigate("/order-confirmation");}else if(type==="address"){window.ELORA.Router.navigate("/addresses");}else if(type==="return"){window.ELORA.Router.navigate("/returns/submitted");}else if(type==="size"){toast(window.ELORA.I18N.language==="ar"?"مقاسك المقترح هو M":"Your suggested size is M","ruler");closeOverlays();}else if(type==="otp"){var code=Array.prototype.map.call(form.querySelectorAll(".otp-input"),function(x){return x.value;}).join("");window.ELORA.Router.navigate(code==="123456"?"/account":"/otp-invalid");}},type==="checkout"?900:500);}
  function updateCatalog(){var grid=document.querySelector("[data-product-grid]");if(!grid)return;var categories=Array.from(new Set(Array.prototype.map.call(document.querySelectorAll("[data-filter-category]:checked"),function(x){return x.value;}))),subcategories=Array.from(new Set(Array.prototype.map.call(document.querySelectorAll("[data-filter-subcategory]:checked"),function(x){return x.value;}))),sort=(document.querySelector("[data-sort]")||{}).value||"newest",products=window.ELORA_DATA.products.slice();if(categories.length)products=products.filter(function(p){return categories.some(function(category){return category==="new-in"?p.badge==="new":p.category===category;});});if(subcategories.length)products=products.filter(function(p){return subcategories.indexOf(p.subcategory)>-1;});if(sort==="low")products.sort(function(a,b){return a.price-b.price;});if(sort==="high")products.sort(function(a,b){return b.price-a.price;});grid.innerHTML=products.map(C().productCard).join("");var count=document.querySelector("[data-results-count]");if(count)count.textContent=products.length+" "+t("shop.results");window.ELORA.Animations.enter();}
  function handleAction(button,action){var id=button.getAttribute("data-id"),index=button.getAttribute("data-index");
    if(action==="open-menu")openOverlay("[data-mobile-menu]");
    else if(action==="open-mini-cart"){if(window.ELORA.Router.parse().path!=="/cart")openMiniCart();}
    else if(action==="close-overlays")closeOverlays();
    else if(action==="open-search"){closeOverlays();var search=document.querySelector("[data-search-overlay]");if(search){search.classList.add("is-open");document.body.classList.add("is-locked");var input=search.querySelector("[data-search-input]");updateSearch(input,search.querySelector("[data-search-results]"));setTimeout(function(){input.focus();},80);}}
    else if(action==="toggle-language"){window.ELORA.I18N.toggle();closeOverlays();window.ELORA.Router.render();}
    else if(action==="open-filters")openOverlay("[data-filter-drawer]");
    else if(action==="clear-filters"){document.querySelectorAll("[data-filter-category],[data-filter-subcategory]").forEach(function(x){x.checked=false;});updateCatalog();}
    else if(action==="toggle-wishlist"){var added=window.ELORA.store.toggleWishlist(id);button.classList.toggle("is-active",added);toast(t(added?"shop.wishlistAdded":"shop.wishlistRemoved"),"heart");if(window.ELORA.Router.parse().path==="/wishlist")window.ELORA.Router.render();}
    else if(action==="quick-view")quickView(id);
    else if(action==="quick-add"){var quickProduct=window.ELORA.store.getProduct(id);window.ELORA.store.addToCart(id,1,quickProduct&&quickProduct.sizes[0]||"ONE","");toast(t("shop.added"),"shopping-bag");closeOverlays();}
    else if(action==="add-product"){var size=document.querySelector("[data-product-size].is-active"),color=document.querySelector("[data-product-color].is-active"),qty=document.querySelector("[data-detail-qty]");if(!size){toast(t("product.selectSize"),"circle-alert");return;}window.ELORA.store.addToCart(id,qty?Number(qty.textContent):1,size.getAttribute("data-product-size"),color?color.getAttribute("data-product-color"):"");toast(t("shop.added"),"shopping-bag");window.ELORA.Animations.buttonSuccess(button);}
    else if(action==="add-look"){[1,3,5].forEach(function(pid){var lookProduct=window.ELORA.store.getProduct(pid);window.ELORA.store.addToCart(pid,1,lookProduct&&lookProduct.sizes[0]||"ONE","");});toast(t("shop.added"),"shopping-bag");}
    else if(action==="detail-qty"){var q=document.querySelector("[data-detail-qty]");q.textContent=Math.max(1,Number(q.textContent)+Number(button.getAttribute("data-delta")));}
    else if(action==="shein-qty"){var quantity=document.querySelector("[data-shein-qty]"),hidden=document.querySelector("[data-shein-quantity]"),next=Math.max(1,Number(quantity.textContent)+Number(button.getAttribute("data-delta")));quantity.textContent=next;if(hidden)hidden.value=next;}
    else if(action==="remove-shein-image"){var form=button.closest("form"),hidden=form&&form.querySelector('[name="imageData"]'),preview=form&&form.querySelector("[data-shein-preview]"),file=form&&form.querySelector("[data-shein-upload]");if(hidden)hidden.value="";if(file)file.value="";if(preview){preview.innerHTML="";preview.classList.remove("has-image");}}
    else if(action==="mini-cart-qty"){window.ELORA.store.changeQuantity(index,button.getAttribute("data-delta"));refreshMiniCart();}
    else if(action==="mini-cart-remove"){window.ELORA.store.removeFromCart(index);refreshMiniCart();toast(t("cart.removed"),"trash-2");}
    else if(action==="apply-mini-promo"){var miniInput=document.querySelector("[data-mini-promo]"),miniCode=(miniInput&&miniInput.value||"").trim().toUpperCase();window.ELORA.store.setPromo(miniCode);if(window.ELORA.store.state.promo)toast(t("cart.promoSuccess"),"badge-percent");else toast(t("cart.invalidPromo"),"circle-alert");refreshMiniCart();}
    else if(action==="cart-qty"){window.ELORA.store.changeQuantity(index,button.getAttribute("data-delta"));window.ELORA.Router.render();}
    else if(action==="remove-cart"){var item=button.closest("[data-cart-item]");if(item&&!window.ELORA.Animations.reduced()){item.style.transition=".3s";item.style.opacity="0";item.style.maxHeight=item.offsetHeight+"px";requestAnimationFrame(function(){item.style.maxHeight="0";item.style.padding="0";});setTimeout(function(){window.ELORA.store.removeFromCart(index);window.ELORA.Router.render();},320);}else{window.ELORA.store.removeFromCart(index);window.ELORA.Router.render();}}
    else if(action==="apply-promo"){var code=(document.querySelector("[data-promo]")||{}).value||"";window.ELORA.store.setPromo(code.toUpperCase());if(window.ELORA.store.state.promo){toast(t("cart.promoSuccess"),"badge-percent");window.ELORA.Router.render();}else toast(t("common.error"),"circle-alert");}
    else if(action==="accordion"){var item=button.closest(".accordion"),open=item.classList.toggle("is-open");button.setAttribute("aria-expanded",String(open));}
    else if(action==="zoom-image"){var gallery=button.closest("[data-product-gallery]"),product=gallery&&window.ELORA.store.getProduct(gallery.getAttribute("data-product-id")),active=button.querySelector(".main-product-image__asset");if(active){showModal('<div class="gallery-lightbox"><img src="'+C().escape(active.getAttribute("src"))+'" alt="'+C().escape(product?C().pick(product.name):t("product.imageOf"))+'" width="1200" height="1600"></div>');}}
    else if(action==="size-assistant")sizeAssistant();
    else if(action==="open-style-quiz")styleQuiz();
    else if(action==="quiz-result"){closeOverlays();window.ELORA.Router.navigate("/shop?category="+button.getAttribute("data-category"));}
    else if(action==="toggle-password"){var form=button.closest("form"),inputs=form.querySelectorAll('input[type="password"],input[type="text"][data-password]'),show=Array.prototype.some.call(inputs,function(x){return x.type==="password";});inputs.forEach(function(x){x.type=show?"text":"password";x.setAttribute("data-password","");});button.textContent=t(show?"auth.hidePassword":"auth.showPassword");}
    else if(action==="resend-otp"){toast(t("auth.resend"),"send");startOtp();}
    else if(action==="recent-search"){var input=document.querySelector("[data-search-input]");input.value=button.getAttribute("data-query");updateSearch(input,document.querySelector("[data-search-results]"));}
    else if(action==="clear-searches"){window.ELORA.store.clearSearches();var input=document.querySelector("[data-search-input]");updateSearch(input,document.querySelector("[data-search-results]"));}
    else if(action==="submit-page-search"){var pageInput=document.querySelector("[data-page-search]");renderPageSearch(pageInput? pageInput.value:"");}
    else if(action==="logout"){window.ELORA.store.setAuth(false);window.ELORA.Router.navigate("/login");}
    else if(action==="cancel-shein-request"){if(window.ELORA.store.cancelSubmittedSpecialRequest(id)){toast(t("shein.cancelSuccess"),"check");window.ELORA.Router.render();}}
  }
  function renderPageSearch(query){var output=document.querySelector("[data-page-search-results]");if(!output)return;query=String(query||"").trim();if(!query){output.innerHTML=searchRows("");return;}window.ELORA.store.addSearch(query);var products=searchProducts(query);output.innerHTML=products.length?'<p class="eyebrow">'+products.length+' '+t("shop.results")+'</p><div class="grid grid--4 product-grid">'+products.map(C().productCard).join("")+'</div>':C().emptyState("search-x",t("search.noResults"),t("search.placeholder"))+C().sheinCta("shein-cta--search-empty");window.ELORA.Animations.enter();}
  function setSheinPreview(form,data){var hidden=form.querySelector('[name="imageData"]'),preview=form.querySelector("[data-shein-preview]");if(hidden)hidden.value=data;if(preview){preview.classList.add("has-image");preview.innerHTML='<img src="'+data+'" alt="'+C().escape(t("shein.previewAlt"))+'"><button class="icon-btn" type="button" data-action="remove-shein-image" aria-label="'+C().escape(t("shein.removeImage"))+'">'+C().icon("x")+'</button>';}if(window.lucide)window.lucide.createIcons();}
  function processSheinImage(file,form){var error=form.querySelector("[data-image-error]"),allowed=["image/jpeg","image/png","image/webp"];if(error)error.textContent="";if(!file)return;if(allowed.indexOf(file.type)===-1){if(error)error.textContent=t("shein.imageError");return;}if(file.size>15*1024*1024){if(error)error.textContent=t("shein.imageTooLarge");return;}var reader=new FileReader();reader.onerror=function(){if(error)error.textContent=t("shein.imageTooLarge");};reader.onload=function(){var img=new Image();img.onerror=function(){if(error)error.textContent=t("shein.imageError");};img.onload=function(){var max=960,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));var ctx=canvas.getContext("2d");ctx.drawImage(img,0,0,canvas.width,canvas.height);var data=canvas.toDataURL("image/webp",.76);if(data.length>850000){var smaller=document.createElement("canvas"),ratio=Math.min(1,720/Math.max(canvas.width,canvas.height));smaller.width=Math.max(1,Math.round(canvas.width*ratio));smaller.height=Math.max(1,Math.round(canvas.height*ratio));smaller.getContext("2d").drawImage(canvas,0,0,smaller.width,smaller.height);data=smaller.toDataURL("image/webp",.62);}if(data.length>1000000){if(error)error.textContent=t("shein.imageTooLarge");return;}setSheinPreview(form,data);};img.src=reader.result;};reader.readAsDataURL(file);}
  function startOtp(){clearInterval(otpTimer);var left=30,button=document.querySelector('[data-action="resend-otp"]'),label=document.querySelector("[data-resend-label]");if(!button||!label)return;button.disabled=true;otpTimer=setInterval(function(){left--;label.textContent=t("auth.resendIn")+" 00:"+String(left).padStart(2,"0");if(left<=0){clearInterval(otpTimer);button.disabled=false;label.textContent=t("auth.resend");}},1000);}
  function bindPage(){closeOverlays();updateCartCounters(false);document.body.classList.remove("has-sticky-purchase");var appRoot=document.getElementById("app"),filterDrawer=document.querySelector("[data-filter-drawer]"),stickyPurchase=document.querySelector(".sticky-purchase");if(appRoot&&filterDrawer)appRoot.appendChild(filterDrawer);if(appRoot&&stickyPurchase){appRoot.appendChild(stickyPurchase);document.body.classList.add("has-sticky-purchase");}var params=window.ELORA.Router.parse().params;injectMobileDepartments(params);if(params.category)document.querySelectorAll('[data-filter-category]').forEach(function(x){x.checked=x.value===params.category;});if(params.subcategory)document.querySelectorAll('[data-filter-subcategory]').forEach(function(x){x.checked=x.value===params.subcategory;});if(document.querySelector(".otp-row"))startOtp();document.querySelectorAll('option[value="One Size"]').forEach(function(option){option.textContent=t("shein.oneSize");});document.querySelectorAll('option[value="Custom / Other"]').forEach(function(option){option.textContent=t("shein.customOther");});document.querySelectorAll('select[name="displayedCurrency"] option[value="Other"]').forEach(function(option){option.textContent=t("shein.otherCurrency");});var input=document.querySelector("[data-page-search]");if(input)setTimeout(function(){input.focus();},100);if(document.body.classList.contains("cart-bump"))setTimeout(function(){document.body.classList.remove("cart-bump");},900);if(window.ELORA.Chatbot)window.ELORA.Chatbot.onRouteChange();}
  function init(){window.ELORA.I18N.set(window.ELORA.I18N.detect(),false);document.addEventListener("elora:store",function(){updateCartCounters(true);});document.addEventListener("click",function(e){var button=e.target.closest("[data-action]");if(button){if(button.tagName==="A")return;handleAction(button,button.getAttribute("data-action"));}var size=e.target.closest("[data-product-size]");if(size){size.parentNode.querySelectorAll("[data-product-size]").forEach(function(x){x.classList.remove("is-active");});size.classList.add("is-active");}var color=e.target.closest("[data-product-color]");if(color){color.parentNode.querySelectorAll("[data-product-color]").forEach(function(x){x.classList.remove("is-active");});color.classList.add("is-active");}var thumb=e.target.closest("[data-gallery-thumb]");if(thumb){thumb.parentNode.querySelectorAll("[data-gallery-thumb]").forEach(function(x){x.classList.remove("is-active");});thumb.classList.add("is-active");var active=document.querySelector("[data-product-image] .main-product-image__asset"),src=thumb.getAttribute("data-image");if(active&&src){active.classList.remove("is-visible");setTimeout(function(){active.src=src;active.classList.add("is-visible");},120);var main=active.closest("[data-product-image]"),all=Array.prototype.slice.call(thumb.parentNode.querySelectorAll("[data-gallery-thumb]"));if(main)main.setAttribute("data-image-index",String(all.indexOf(thumb)));}}var quiz=e.target.closest("[data-quiz]");if(quiz){quiz.parentNode.querySelectorAll("[data-quiz]").forEach(function(x){x.classList.remove("is-active");});quiz.classList.add("is-active");}});
    document.addEventListener("submit",function(e){var form=e.target.closest("[data-form]");if(form){e.preventDefault();handleForm(form);}});
    document.addEventListener("input",function(e){if(e.target.matches("[data-search-input]")){updateSearch(e.target,document.querySelector("[data-search-results]"));}if(e.target.matches("[data-page-search]"))renderPageSearch(e.target.value);if(e.target.matches(".otp-input")){e.target.value=e.target.value.replace(/\D/g,"").slice(0,1);if(e.target.value&&e.target.nextElementSibling)e.target.nextElementSibling.focus();}if(e.target.matches("[data-upload]")){var file=e.target.files&&e.target.files[0],out=document.querySelector("[data-upload-preview]");if(file&&out){var reader=new FileReader();reader.onload=function(){out.innerHTML='<img class="upload-preview" src="'+reader.result+'" alt="'+C().escape(t("shein.previewAlt"))+'">';};reader.readAsDataURL(file);}}});
    ["dragenter","dragover"].forEach(function(eventName){document.addEventListener(eventName,function(e){var zone=e.target.closest&&e.target.closest("[data-shein-drop]");if(zone){e.preventDefault();zone.classList.add("is-dragging");}});});
    ["dragleave","drop"].forEach(function(eventName){document.addEventListener(eventName,function(e){var zone=e.target.closest&&e.target.closest("[data-shein-drop]");if(!zone)return;e.preventDefault();zone.classList.remove("is-dragging");if(eventName==="drop"){var dropped=e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files[0],requestForm=zone.closest("form");if(dropped&&requestForm)processSheinImage(dropped,requestForm);}});});
    document.addEventListener("change",function(e){if(e.target.matches("[data-sort],[data-filter-category],[data-filter-subcategory]"))updateCatalog();if(e.target.matches("[data-shein-upload]")){var form=e.target.closest("form"),file=e.target.files&&e.target.files[0];if(form&&file)processSheinImage(file,form);}if(e.target.matches("[data-mini-size]")){var changed=window.ELORA.store.changeSize(e.target.getAttribute("data-index"),e.target.value);if(changed){refreshMiniCart();toast(t("cart.sizeUpdated"),"ruler");}}if(e.target.matches("[data-cart-size]")){var cartChanged=window.ELORA.store.changeSize(e.target.getAttribute("data-index"),e.target.value);if(cartChanged){toast(t("cart.sizeUpdated"),"ruler");window.ELORA.Router.render();}}});
    document.addEventListener("keydown",function(e){if(e.key==="Escape")closeOverlays();if(e.key==="Enter"&&e.target.matches("[data-search-input]")){window.ELORA.store.addSearch(e.target.value);var results=searchProducts(e.target.value);if(results[0])window.ELORA.Router.navigate("/product/"+results[0].id);}if(e.key==="Enter"&&e.target.matches("[data-mini-promo]")){e.preventDefault();var applyButton=document.querySelector('[data-action="apply-mini-promo"]');if(applyButton)handleAction(applyButton,"apply-mini-promo");}});
    window.addEventListener("online",function(){toast(t("common.success"),"wifi");});
    window.addEventListener("offline",function(){toast(t("states.offlineTitle"),"wifi-off");});
    window.ELORA.Router.init();
    if(window.ELORA.Chatbot)window.ELORA.Chatbot.init();
    window.addEventListener("load",function(){setTimeout(function(){document.getElementById("preloader").classList.add("is-hidden");},350);});setTimeout(function(){var p=document.getElementById("preloader");if(p)p.classList.add("is-hidden");},1200);
  }
  window.ELORA.App={init:init,bindPage:bindPage,toast:toast,closeOverlays:closeOverlays};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
