(function () {
  "use strict";
  window.ELORA = window.ELORA || {};

  var DATA=window.ELORA_CHATBOT_DATA,MAX_LENGTH=700,initialized=false,root,panel,launcher,messagesNode,inputNode,counterNode,latestButton,nudgeNode;
  var open=false,typing=false,typingTimer=null,proactiveTimer=null,responseQueue=[],fuseIndex=null,searchDocuments=[];

  function t(key){return window.ELORA.I18N.t(key);}
  function lang(){return window.ELORA.I18N.language;}
  function pick(value){return value&&typeof value==="object"&&value[lang()]!==undefined?value[lang()]:value;}
  function interpolate(text,vars){return String(text||"").replace(/\{(\w+)\}/g,function(_,key){return vars&&vars[key]!==undefined?String(vars[key]):"";});}
  function copy(key,vars){return interpolate(pick(DATA.copy[key]),vars);}
  function now(){return new Date().toISOString();}
  function uid(){return "chat-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);}
  function safeStorage(storage,key,value){try{if(value===undefined)return storage.getItem(key);storage.setItem(key,value);return true;}catch(e){return value===undefined?null:false;}}
  function normalizeArabic(value){return String(value||"").replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,"").replace(/[أإآٱ]/g,"ا").replace(/ى/g,"ي").replace(/ؤ/g,"و").replace(/ئ/g,"ي").replace(/ة/g,"ه");}
  function normalize(value){return normalizeArabic(value).toLowerCase().replace(/[ًٌٍَُِّْـ]/g,"").replace(/[^a-z0-9\u0600-\u06ff#.+\-\s]/g," ").replace(/\s+/g," ").trim();}
  function normalizedDigits(value){var ar="٠١٢٣٤٥٦٧٨٩",fa="۰۱۲۳۴۵۶۷۸۹";return String(value||"").replace(/[٠-٩]/g,function(d){return ar.indexOf(d);}).replace(/[۰-۹]/g,function(d){return fa.indexOf(d);});}
  function productById(id){return window.ELORA.store.getProduct(Number(id));}
  function route(){return window.ELORA.Router?window.ELORA.Router.parse():{path:(location.hash||"#/home").slice(1).split("?")[0],params:{}};}
  function currentProduct(){var match=route().path.match(/^\/product\/(\d+)$/);return match?productById(match[1]):null;}
  function money(value){return window.ELORA.Components.money(value);}
  function moneyFor(value,language){return new Intl.NumberFormat(language==="ar"?"ar-EG":"en-EG",{maximumFractionDigits:0}).format(value)+" "+(language==="ar"?"ج.م":"EGP");}
  function state(){return window.ELORA.store.state.chatState||{mode:"idle",step:"",answers:{},lastProductIds:[],resultOffset:0};}
  function saveState(next){return window.ELORA.store.setChatState(next);}
  function history(){return window.ELORA.store.state.chatHistory||[];}
  function saveHistory(list){return window.ELORA.store.setChatHistory(list.slice(-100));}
  function messageText(message){return message.key?copy(message.key,message.vars):String(message.text||"");}
  function makeMessage(role,options){options=options||{};return {id:uid(),role:role,text:String(options.text||"").slice(0,1400),key:options.key||"",vars:options.vars||null,payload:options.payload||null,timestamp:now(),delivery:"sent"};}
  function addMessage(message,markUnread){var list=history().slice();list.push(message);saveHistory(list);if(markUnread&&!open)window.ELORA.store.setChatUnread((window.ELORA.store.state.chatUnread||0)+1);renderHistory(true);updateUnread();return message;}
  function addUser(text){return addMessage(makeMessage("user",{text:text}),false);}
  function addAssistant(options){return addMessage(makeMessage("assistant",options),true);}
  function queueAssistant(options,delay){responseQueue.push({options:options,delay:Math.max(280,Math.min(850,delay||520))});runResponseQueue();}
  function runResponseQueue(){if(typing||!responseQueue.length)return;var next=responseQueue.shift();typing=true;renderTyping();typingTimer=setTimeout(function(){typing=false;removeTyping();addAssistant(next.options);runResponseQueue();},next.delay);}
  function clearReplyQueue(){clearTimeout(typingTimer);typing=false;responseQueue=[];removeTyping();}

  function logoMarkup(){return '<img src="assets/icons/elora-concierge.svg" alt="" width="42" height="42">';}
  function starterActions(){return [
    {labelKey:"chatbot.starterChoose",value:"start-finder"},{labelKey:"chatbot.starterSearch",value:"ask-search"},{labelKey:"chatbot.starterSize",value:"start-size"},
    {labelKey:"chatbot.starterTrack",value:"start-tracking"},{labelKey:"chatbot.starterShein",value:"shein-info"},{labelKey:"chatbot.starterPolicies",value:"policies"},{labelKey:"chatbot.starterContact",value:"start-contact"}
  ];}
  function buildShell(){
    if(!root)return;
    var unread=Number(window.ELORA.store.state.chatUnread||0);
    root.innerHTML='<div class="concierge-nudge" data-chat-nudge hidden><button type="button" class="concierge-nudge__body" data-chat-command="open"><span data-chat-nudge-text></span></button><button type="button" class="concierge-nudge__close" data-chat-command="dismiss-nudge" aria-label="'+t("chatbot.nudgeClose")+'">×</button></div>'+
      '<button class="concierge-launcher" type="button" data-chat-command="toggle" aria-label="'+t("chatbot.open")+'" aria-expanded="'+(open?"true":"false")+'"><span class="concierge-launcher__logo">'+logoMarkup()+'</span><span class="concierge-launcher__close" aria-hidden="true"><span></span><span></span></span><span class="concierge-unread" data-chat-unread'+(unread?"":" hidden")+'>'+unread+'</span><span class="concierge-tooltip" role="tooltip">'+t("chatbot.tooltip")+'</span></button>'+
      '<section class="concierge-panel" data-chat-panel role="dialog" aria-labelledby="concierge-title" aria-describedby="concierge-automation" aria-hidden="'+(open?"false":"true")+'" tabindex="-1">'+
        '<header class="concierge-header"><button class="concierge-header__back" type="button" data-chat-command="minimize" aria-label="'+t("chatbot.back")+'"><i data-lucide="arrow-left"></i></button><span class="concierge-header__mark">'+logoMarkup()+'</span><div class="concierge-header__copy"><h2 id="concierge-title">'+t("chatbot.name")+'</h2><p>'+t("chatbot.tagline")+'</p><span><i aria-hidden="true"></i>'+t("chatbot.ready")+'</span></div><div class="concierge-header__actions"><button type="button" data-chat-command="new" aria-label="'+t("chatbot.newChat")+'"><i data-lucide="rotate-ccw"></i></button><button type="button" data-chat-command="minimize" aria-label="'+t("chatbot.minimize")+'"><i data-lucide="minus"></i></button><button type="button" data-chat-command="close" aria-label="'+t("chatbot.close")+'"><i data-lucide="x"></i></button></div></header>'+
        '<p class="concierge-automation" id="concierge-automation"><i data-lucide="sparkles"></i><span>'+t("chatbot.automatedNotice")+'</span></p><div class="concierge-messages" data-chat-messages aria-live="polite" aria-relevant="additions text" tabindex="0"></div>'+
        '<button class="concierge-latest" type="button" data-chat-command="latest" hidden><i data-lucide="arrow-down"></i>'+t("chatbot.scrollLatest")+'</button>'+
        '<footer class="concierge-composer"><p class="concierge-security"><i data-lucide="shield-check"></i>'+t("chatbot.security")+'</p><div class="concierge-compose-row"><textarea data-chat-input rows="1" maxlength="'+MAX_LENGTH+'" placeholder="'+t("chatbot.placeholder")+'" aria-label="'+t("chatbot.placeholder")+'"></textarea><button type="button" data-chat-command="send" aria-label="'+t("chatbot.send")+'"><i data-lucide="send"></i></button></div><span class="concierge-counter" data-chat-counter hidden></span></footer></section>';
    panel=root.querySelector("[data-chat-panel]");launcher=root.querySelector(".concierge-launcher");messagesNode=root.querySelector("[data-chat-messages]");inputNode=root.querySelector("[data-chat-input]");counterNode=root.querySelector("[data-chat-counter]");latestButton=root.querySelector(".concierge-latest");nudgeNode=root.querySelector("[data-chat-nudge]");
    setOpenState(open,false);renderHistory(false);updateUnread();if(window.lucide)window.lucide.createIcons();
  }

  function timeLabel(value){try{return new Intl.DateTimeFormat(lang()==="ar"?"ar-EG":"en-EG",{hour:"2-digit",minute:"2-digit"}).format(new Date(value));}catch(e){return "";}}
  function resolveLabel(action){return action.labelKey?t(action.labelKey):pick(action.label)||String(action.label||"");}
  function renderActions(container,actions){if(!actions||!actions.length)return;var wrap=document.createElement("div");wrap.className="concierge-quick-actions";actions.forEach(function(action,index){var button=document.createElement("button");button.type="button";button.className="concierge-quick";button.dataset.chatAction=action.value;button.style.setProperty("--chat-index",index);button.textContent=resolveLabel(action);wrap.appendChild(button);});container.appendChild(wrap);}
  function badgeLabel(product){if(!product.badge)return "";return product.badge==="new"?t("shop.newest"):product.badge==="limited"?t("shop.filterTitle"):t("shop.newest");}
  function sizeLabelFor(size,language){if(size==="One Size"||size==="ONE")return window.ELORA_I18N[language].shein.oneSize;if(size==="Custom / Other")return window.ELORA_I18N[language].shein.customOther;return size;}
  function sizeLabel(size){return sizeLabelFor(size,lang());}
  function renderProductCard(product,reason){
    var card=document.createElement("article");card.className="concierge-product";card.dataset.chatProduct=product.id;
    var media=document.createElement("div");media.className="concierge-product__media";media.style.setProperty("--chat-art",product.art||product.colors[0]||"#6f2638");var shape=document.createElement("span");shape.className="concierge-product__shape";media.appendChild(shape);
    var badge=badgeLabel(product);if(badge){var badgeNode=document.createElement("span");badgeNode.className="concierge-product__badge";badgeNode.textContent=badge;media.appendChild(badgeNode);}card.appendChild(media);
    var body=document.createElement("div");body.className="concierge-product__body";var title=document.createElement("h3");title.textContent=pick(product.name);body.appendChild(title);
    if(reason){var why=document.createElement("p");why.className="concierge-product__reason";why.textContent=reason;body.appendChild(why);}
    var prices=document.createElement("div");prices.className="concierge-product__prices";var price=document.createElement("strong");price.textContent=money(product.price);prices.appendChild(price);if(product.oldPrice){var old=document.createElement("s");old.textContent=money(product.oldPrice);prices.appendChild(old);}body.appendChild(prices);
    var swatches=document.createElement("div");swatches.className="concierge-product__swatches";swatches.setAttribute("aria-label",t("product.color"));(product.colors||[]).forEach(function(color,index){var swatch=document.createElement("button");swatch.type="button";swatch.className="concierge-product__swatch"+(index===0?" is-active":"");swatch.dataset.chatColor=color;swatch.style.background=color;swatch.setAttribute("aria-label",t("product.color")+" "+(index+1));swatches.appendChild(swatch);});body.appendChild(swatches);
    var sizeWrap=document.createElement("label");sizeWrap.className="concierge-product__size";var sizeText=document.createElement("span");sizeText.textContent=t("chatbot.availableSizes");var select=document.createElement("select");select.dataset.chatSize="";select.setAttribute("aria-label",t("chatbot.selectSize"));(product.sizes||[]).forEach(function(size){var option=document.createElement("option");option.value=size;option.textContent=sizeLabel(size);select.appendChild(option);});sizeWrap.appendChild(sizeText);sizeWrap.appendChild(select);body.appendChild(sizeWrap);
    var availability=document.createElement("p");availability.className="concierge-product__availability";availability.textContent=t("chatbot.availabilityReview");body.appendChild(availability);
    var actions=document.createElement("div");actions.className="concierge-product__actions";var view=document.createElement("button");view.type="button";view.dataset.chatProductAction="view";view.textContent=t("chatbot.viewProduct");var add=document.createElement("button");add.type="button";add.dataset.chatProductAction="add";add.textContent=t("chatbot.addCart");var wish=document.createElement("button");wish.type="button";wish.className="concierge-product__wish";wish.dataset.chatProductAction="wishlist";wish.setAttribute("aria-label",window.ELORA.store.isWishlisted(product.id)?t("chatbot.removeWishlist"):t("chatbot.wishlist"));wish.innerHTML='<i data-lucide="heart"></i>';wish.classList.toggle("is-active",window.ELORA.store.isWishlisted(product.id));actions.appendChild(view);actions.appendChild(add);actions.appendChild(wish);body.appendChild(actions);card.appendChild(body);return card;
  }
  function renderPayload(container,payload){if(!payload)return;if(payload.kind==="products"){var grid=document.createElement("div");grid.className="concierge-products";(payload.ids||[]).slice(0,3).forEach(function(id){var product=productById(id);if(product)grid.appendChild(renderProductCard(product,payload.reasonKey?copy(payload.reasonKey):""));});container.appendChild(grid);if(payload.hasMore)renderActions(container,[{labelKey:"chatbot.showMore",value:"show-more"}]);}if(payload.kind==="actions")renderActions(container,payload.actions||[]);if(payload.kind==="order")renderActions(container,[{labelKey:"chatbot.openTracking",value:"navigate:"+payload.href}]);if(payload.kind==="return")renderActions(container,[{labelKey:"chatbot.openReturns",value:"navigate:#/returns"}]);if(payload.kind==="shein")renderActions(container,[{labelKey:"chatbot.openShein",value:"navigate-shein"}]);if(payload.kind==="contact"){var contactActions=[{labelKey:"chatbot.copySummary",value:"copy-summary"}],config=window.ELORA_CONFIG||{};if(/^\+?\d{8,15}$/.test(String(config.whatsappNumber||"").replace(/[\s()-]/g,"")))contactActions.unshift({labelKey:"chatbot.continueWhatsApp",value:"contact-whatsapp"});if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(config.contactEmail||"")))contactActions.unshift({labelKey:"chatbot.continueEmail",value:"contact-email"});renderActions(container,contactActions);}}
  function renderMessage(message){var row=document.createElement("div");row.className="concierge-message concierge-message--"+message.role;row.dataset.messageId=message.id;var bubble=document.createElement("div");bubble.className="concierge-bubble";var text=document.createElement("p");text.textContent=messageText(message);bubble.appendChild(text);renderPayload(bubble,message.payload);var meta=document.createElement("span");meta.className="concierge-message__meta";meta.textContent=timeLabel(message.timestamp)+(message.role==="user"?" · "+t("chatbot.messageSent"):"");bubble.appendChild(meta);row.appendChild(bubble);return row;}
  function nearBottom(){return !messagesNode||messagesNode.scrollHeight-messagesNode.scrollTop-messagesNode.clientHeight<120;}
  function renderHistory(newMessage){if(!messagesNode)return;var follow=!newMessage||nearBottom();messagesNode.textContent="";history().forEach(function(message){messagesNode.appendChild(renderMessage(message));});if(typing)renderTyping();if(follow)requestAnimationFrame(scrollLatest);else if(latestButton)latestButton.hidden=false;if(window.lucide)window.lucide.createIcons();}
  function renderTyping(){if(!messagesNode||messagesNode.querySelector("[data-chat-typing]"))return;var row=document.createElement("div");row.className="concierge-message concierge-message--assistant concierge-message--typing";row.dataset.chatTyping="";row.setAttribute("aria-label",t("chatbot.typing"));var bubble=document.createElement("div");bubble.className="concierge-bubble";for(var i=0;i<3;i++)bubble.appendChild(document.createElement("i"));row.appendChild(bubble);messagesNode.appendChild(row);if(nearBottom())scrollLatest();}
  function removeTyping(){var node=messagesNode&&messagesNode.querySelector("[data-chat-typing]");if(node)node.remove();}
  function scrollLatest(){if(!messagesNode)return;messagesNode.scrollTo({top:messagesNode.scrollHeight,behavior:window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});if(latestButton)latestButton.hidden=true;}
  function updateUnread(){if(!root)return;var value=Number(window.ELORA.store.state.chatUnread||0),badge=root.querySelector("[data-chat-unread]");if(badge){badge.textContent=value>99?"99+":value;badge.hidden=!value;}}

  function setOpenState(next,focus){open=!!next;if(!root)return;root.classList.toggle("is-open",open);if(panel){panel.setAttribute("aria-hidden",open?"false":"true");panel.setAttribute("aria-modal",window.matchMedia&&window.matchMedia("(max-width: 767px)").matches?"true":"false");}if(launcher){launcher.setAttribute("aria-expanded",open?"true":"false");launcher.setAttribute("aria-label",t(open?"chatbot.close":"chatbot.open"));}document.body.classList.toggle("chat-open",open&&window.matchMedia&&window.matchMedia("(max-width: 767px)").matches);window.ELORA.store.setChatPreferences({minimized:!open,language:lang()});if(open){window.ELORA.store.setChatUnread(0);updateUnread();hideNudge(true);setTimeout(function(){if(focus&&inputNode)inputNode.focus();scrollLatest();},80);}else if(focus&&launcher)launcher.focus();}
  function openChat(){setOpenState(true,true);}
  function closeChat(){setOpenState(false,true);}
  function newConversation(){clearReplyQueue();window.ELORA.store.clearChat();addAssistant({key:"reset",payload:{kind:"actions",actions:starterActions()}});renderHistory(false);if(inputNode)inputNode.focus();}

  function initSearch(){searchDocuments=window.ELORA_DATA.products.map(function(product){var category=window.ELORA_DATA.categories.find(function(c){return c.id===product.category;}),subcategory=category&&(category.subcategories||[]).find(function(s){return s.id===product.subcategory;}),colorTerms=[];DATA.colors.forEach(function(color){if((product.colors||[]).some(function(hex){return color.hex.indexOf(String(hex).toLowerCase())>-1;}))colorTerms=colorTerms.concat(color.terms);});return {product:product,search:normalize([product.name.en,product.name.ar,product.description.en,product.description.ar,category&&category.name.en,category&&category.name.ar,subcategory&&subcategory.name.en,subcategory&&subcategory.name.ar,product.category,product.subcategory,(product.sizes||[]).join(" "),colorTerms.join(" ")].filter(Boolean).join(" "))};});if(window.Fuse)fuseIndex=new Fuse(searchDocuments,{keys:["search"],includeScore:true,threshold:.44,ignoreLocation:true});}
  function containsTerm(text,term){term=normalize(term);return !!(term&&((" "+text+" ").indexOf(" "+term+" ")>-1||(term.length>3&&text.indexOf(term)>-1)));}
  function extractFacets(query){var n=normalize(normalizedDigits(query)),facets={query:n,category:"",subcategory:"",color:"",budget:null,size:""};Object.keys(DATA.subcategoryAliases).some(function(id){return DATA.subcategoryAliases[id].some(function(term){if(containsTerm(n,term)){facets.subcategory=id;return true;}return false;});});Object.keys(DATA.categoryAliases).some(function(id){return DATA.categoryAliases[id].some(function(term){if(containsTerm(n,term)){facets.category=id;return true;}return false;});});DATA.colors.some(function(color){return color.terms.some(function(term){if(containsTerm(n,term)){facets.color=color.id;return true;}return false;});});var numberMatch=normalizedDigits(query).match(/(?:under|less than|below|اقل من|تحت|حد اقصي|ميزانيه)?\s*(\d{2,6})/i);if(numberMatch)facets.budget=Number(numberMatch[1]);var sizeMatch=n.match(/(?:^|\s)(?:(?:size|مقاس)\s*)?(xxl|xl|xs|s|m|l|3[7-9]|40|one|30 ml)(?=$|\s)/i);if(sizeMatch)facets.size=sizeMatch[1].toUpperCase();return facets;}
  function colorMatches(product,colorId){var color=DATA.colors.find(function(c){return c.id===colorId;});return !color||(product.colors||[]).some(function(hex){return color.hex.indexOf(String(hex).toLowerCase())>-1;});}
  function productMatchesType(product,type){if(!type)return true;if(type==="bags")return product.category==="bags-shoes"&&/bag/.test(product.subcategory);if(type==="shoes")return product.category==="bags-shoes"&&!/bag/.test(product.subcategory);if(type==="beauty")return product.category==="accessories-beauty"&&["beauty","skincare"].indexOf(product.subcategory)>-1;if(type==="accessories")return product.category==="accessories-beauty"&&["beauty","skincare"].indexOf(product.subcategory)===-1;return product.category===type;}
  function searchProducts(query,relaxed){if(!searchDocuments.length)initSearch();var facets=extractFacets(query),ranked=fuseIndex&&facets.query?fuseIndex.search(facets.query).map(function(result){return {product:result.item.product,fuse:1-(result.score||0)};}):searchDocuments.map(function(doc){return {product:doc.product,fuse:0};});var seen={},results=[];ranked.concat(searchDocuments.map(function(doc){return {product:doc.product,fuse:0};})).forEach(function(entry){var p=entry.product;if(seen[p.id])return;seen[p.id]=true;var strict=(!facets.category||p.category===facets.category)&&(!facets.subcategory||p.subcategory===facets.subcategory)&&(!facets.budget||p.price<=facets.budget)&&(!facets.color||colorMatches(p,facets.color))&&(!facets.size||(p.sizes||[]).map(function(s){return s.toUpperCase();}).indexOf(facets.size)>-1);if(strict||relaxed){var score=entry.fuse+(facets.category&&p.category===facets.category?3:0)+(facets.subcategory&&p.subcategory===facets.subcategory?4:0)+(facets.budget&&p.price<=facets.budget?2:0)+(facets.color&&colorMatches(p,facets.color)?2:0);results.push({product:p,score:score});}});results.sort(function(a,b){return b.score-a.score||a.product.price-b.product.price;});return results.map(function(x){return x.product;});}
  function showProducts(products,introKey,reasonKey){products=products||[];if(!products.length){var current=state();current.pendingQuery=current.pendingQuery||"";saveState(current);queueAssistant({key:"noResults",payload:{kind:"actions",actions:[{labelKey:"chatbot.alternatives",value:"alternatives"},{labelKey:"chatbot.requestShein",value:"navigate-shein"}]}},500);return;}var currentState=state();currentState.lastProductIds=products.map(function(p){return p.id;});currentState.resultOffset=3;saveState(currentState);queueAssistant({key:introKey||"productIntro",payload:{kind:"products",ids:currentState.lastProductIds.slice(0,3),hasMore:currentState.lastProductIds.length>3,reasonKey:reasonKey||""}},540);}

  function intentScores(text){var n=normalize(text),scores=[];Object.keys(DATA.intents).forEach(function(intent){var score=0;DATA.intents[intent].forEach(function(term){var normalized=normalize(term);if(n===normalized)score+=3;else if(containsTerm(n,normalized))score+=normalized.indexOf(" ")>-1?2:1;});if(score)scores.push({intent:intent,score:score});});scores.sort(function(a,b){return b.score-a.score;});return {intent:scores[0]?scores[0].intent:"unknown",confidence:scores[0]?Math.min(1,scores[0].score/3):0,alternatives:scores.slice(1,4).map(function(x){return x.intent;})};}
  function unknownActions(){return [{labelKey:"chatbot.starterSearch",value:"ask-search"},{labelKey:"chatbot.starterChoose",value:"start-finder"},{labelKey:"chatbot.starterContact",value:"start-contact"}];}
  function hasSensitiveData(text){var n=normalize(text),word=DATA.sensitivePatterns.some(function(term){return n.indexOf(normalize(term))>-1;}),longNumber=normalizedDigits(text).replace(/\D/g,"").length>=13;return word||longNumber;}
  function statusText(status){var value=t("orders."+status);return value==="orders."+status?String(status||t("chatbot.statusPending")):value;}
  function findOrder(number){var normalized=String(number||"").trim().toUpperCase(),local=window.ELORA.store.getOrder(normalized);if(local)return {order:local,local:true};var mock=(window.ELORA_DATA.orders||[]).find(function(order){return String(order.id).toUpperCase()===normalized;});return mock?{order:mock,local:false}:null;}
  function handleTrackingNumber(text){var match=String(text||"").toUpperCase().match(/EL[-\s]?\d{4,}/),number=match?match[0].replace(/\s/g,"-"):String(text||"").trim().toUpperCase(),found=findOrder(number);var current=state();current.mode="idle";current.step="";saveState(current);if(!found){queueAssistant({key:"trackingMissing",payload:{kind:"actions",actions:[{labelKey:"chatbot.starterContact",value:"start-contact"}]}},500);return;}queueAssistant({key:"trackingFound",vars:{id:found.order.id,status:statusText(found.order.status||"pending_review")},payload:{kind:"order",href:"#/tracking?order="+encodeURIComponent(found.order.id)}},500);}
  function startTracking(){var current=state();current.mode="tracking";current.step="order";saveState(current);queueAssistant({key:"trackingAsk"},420);}
  function startSize(){var product=currentProduct(),current=state();if(product){queueAssistant({key:"sizeProduct",vars:{sizes:(product.sizes||[]).map(sizeLabel).join("، ")},payload:{kind:"products",ids:[product.id]}},460);queueAssistant({key:"sizeDisclaimer"},320);return;}current.mode="size";current.step="product";saveState(current);queueAssistant({key:"sizeStart"},420);}
  function handleSizeQuery(text){var products=searchProducts(text,false),current=state();current.mode="idle";current.step="";saveState(current);if(!products.length){showProducts([],"productIntro");return;}var product=products[0];queueAssistant({key:"sizeProduct",vars:{sizes:(product.sizes||[]).map(sizeLabel).join("، ")},payload:{kind:"products",ids:[product.id]}},500);queueAssistant({key:"sizeDisclaimer"},330);}

  function finderActions(step){if(step==="category")return [{labelKey:"chatbot.typeFashion",value:"finder-category:fashion"},{labelKey:"chatbot.typeBags",value:"finder-category:bags"},{labelKey:"chatbot.typeShoes",value:"finder-category:shoes"},{labelKey:"chatbot.typeAccessories",value:"finder-category:accessories"},{labelKey:"chatbot.typeBeauty",value:"finder-category:beauty"}];if(step==="occasion")return [{labelKey:"chatbot.occasionDaily",value:"finder-occasion:daily"},{labelKey:"chatbot.occasionWork",value:"finder-occasion:work"},{labelKey:"chatbot.occasionUniversity",value:"finder-occasion:university"},{labelKey:"chatbot.occasionOuting",value:"finder-occasion:outing"},{labelKey:"chatbot.occasionEvent",value:"finder-occasion:occasion"},{labelKey:"chatbot.occasionGift",value:"finder-occasion:gift"}];if(step==="color")return DATA.colors.map(function(c){return {label:c.labels,value:"finder-color:"+c.id};}).concat([{labelKey:"chatbot.colorAny",value:"finder-color:any"}]);if(step==="style")return DATA.styles.map(function(style){var cap=style.charAt(0).toUpperCase()+style.slice(1);return {labelKey:"chatbot.style"+cap,value:"finder-style:"+style};});return [];}
  function budgetActions(){var prices=window.ELORA_DATA.products.map(function(p){return p.price;}).sort(function(a,b){return a-b;}),low=Math.ceil(prices[Math.floor((prices.length-1)/3)]/100)*100,mid=Math.ceil(prices[Math.floor((prices.length-1)*2/3)]/100)*100;return [{label:{ar:"حتى "+moneyFor(low,"ar"),en:"Up to "+moneyFor(low,"en")},value:"finder-budget:"+low},{label:{ar:"حتى "+moneyFor(mid,"ar"),en:"Up to "+moneyFor(mid,"en")},value:"finder-budget:"+mid},{labelKey:"chatbot.budgetOpen",value:"finder-budget:open"}];}
  function finderSizeActions(answer){var products=window.ELORA_DATA.products.filter(function(p){return productMatchesType(p,answer.category);}),sizes=[];products.forEach(function(p){(p.sizes||[]).forEach(function(size){if(sizes.indexOf(size)===-1)sizes.push(size);});});return sizes.map(function(size){return {label:{ar:sizeLabelFor(size,"ar"),en:sizeLabelFor(size,"en")},value:"finder-size:"+size};});}
  function askFinder(step){var current=state();current.mode="finder";current.step=step;saveState(current);var key="finder"+step.charAt(0).toUpperCase()+step.slice(1),actions=step==="budget"?budgetActions():step==="size"?finderSizeActions(current.answers||{}):finderActions(step);queueAssistant({key:key,payload:{kind:"actions",actions:actions}},420);}
  function startFinder(){var current=state();current.mode="finder";current.step="category";current.answers={};saveState(current);askFinder("category");}
  function occasionScore(product,value){var map={daily:["sets","tops","handbags","skincare","sunglasses"],work:["sets","tops","handbags"],university:["sets","tops","handbags","sunglasses"],outing:["dresses","tops","heels","jewelry","sunglasses"],occasion:["dresses","heels","jewelry"],gift:["jewelry","skincare","handbags"]};return map[value]&&map[value].indexOf(product.subcategory)>-1?2:0;}
  function styleScore(product,value){var map={classic:["dresses","handbags","heels","jewelry"],casual:["sets","tops","sunglasses","skincare"],elegant:["dresses","heels","jewelry","handbags"],trendy:["sets","sunglasses","tops"],minimal:["tops","handbags","skincare"]};return map[value]&&map[value].indexOf(product.subcategory)>-1?1.5:0;}
  function finishFinder(){var answer=state().answers||{},products=window.ELORA_DATA.products.filter(function(p){return productMatchesType(p,answer.category)&&(!answer.budget||p.price<=answer.budget)&&(!answer.color||answer.color==="any"||colorMatches(p,answer.color))&&(!answer.size||(p.sizes||[]).indexOf(answer.size)>-1);});if(!products.length)products=window.ELORA_DATA.products.filter(function(p){return productMatchesType(p,answer.category)&&(!answer.budget||p.price<=answer.budget);});products.sort(function(a,b){return occasionScore(b,answer.occasion)+styleScore(b,answer.style)-occasionScore(a,answer.occasion)-styleScore(a,answer.style)||a.price-b.price;});var current=state();current.mode="idle";current.step="";current.lastProductIds=products.map(function(p){return p.id;});current.resultOffset=3;saveState(current);showProducts(products,"recommendationIntro","recommendationReason");}
  function handleFinderAction(value){var bits=value.split(":"),field=bits[0].replace("finder-",""),selected=bits.slice(1).join(":"),current=state();current.answers=current.answers||{};current.answers[field]=field==="budget"&&selected!=="open"?Number(selected):selected==="open"?null:selected;saveState(current);if(field==="category")askFinder("occasion");else if(field==="occasion")askFinder("budget");else if(field==="budget")askFinder("color");else if(field==="color"){if(["fashion","shoes"].indexOf(current.answers.category)>-1)askFinder("size");else askFinder("style");}else if(field==="size")askFinder("style");else if(field==="style")finishFinder();}
  function handleFinderText(text){var current=state(),step=current.step,n=normalize(text);if(step==="category"){var type="";if(/شنط|حقيبه|\bbag/.test(n))type="bags";else if(/حذاء|احذيه|كعب|\bshoe|heel/.test(n))type="shoes";else if(/جمال|عنايه|سيروم|beauty|skin/.test(n))type="beauty";else if(/اكسسوار|مجوهر|عقد|نظاره|access|jewel/.test(n))type="accessories";else if(/ملابس|ازياء|فستان|بلوز|fashion|dress|top/.test(n))type="fashion";if(type){handleFinderAction("finder-category:"+type);return;}}if(step==="budget"){var amount=normalizedDigits(text).match(/\d{2,6}/);if(amount){handleFinderAction("finder-budget:"+amount[0]);return;}if(/مفتوح|open|any/.test(n)){handleFinderAction("finder-budget:open");return;}}if(step==="color"){var color=DATA.colors.find(function(c){return c.terms.some(function(term){return containsTerm(n,term);});});if(color){handleFinderAction("finder-color:"+color.id);return;}if(/اي لون|مش مهم|any/.test(n)){handleFinderAction("finder-color:any");return;}}if(step==="size"){var available=finderSizeActions(current.answers||{}).find(function(a){return normalize(a.value.split(":").slice(1).join(":"))===n;});if(available){handleFinderAction(available.value);return;}}queueAssistant({key:"unknown",payload:{kind:"actions",actions:step==="budget"?budgetActions():step==="size"?finderSizeActions(current.answers||{}):finderActions(step)}},420);}

  function startContact(){var current=state();current.mode="contact";current.step="name";current.contact={};saveState(current);queueAssistant({key:"contactIntro"},460);}
  function validContact(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)||/^[+\d][\d\s()\-]{7,}$/.test(value);}
  function handleContact(text){var current=state();current.contact=current.contact||{};if(current.step==="name"){current.contact.name=text.slice(0,80);current.step="contact";saveState(current);queueAssistant({key:"contactAskContact"},420);return;}if(current.step==="contact"){if(!validContact(text)){queueAssistant({key:"contactInvalid"},380);return;}current.contact.contact=text.slice(0,120);current.step="topic";saveState(current);queueAssistant({key:"contactAskTopic"},420);return;}if(current.step==="topic"){current.contact.topic=text.slice(0,160);current.step="message";saveState(current);queueAssistant({key:"contactAskMessage"},420);return;}if(current.step==="message"){current.contact.message=text.slice(0,700);current.contact.language=lang();current.contact.conversationSummary=conversationSummary().slice(0,4000);window.ELORA.store.addContactRequest(current.contact);current.mode="idle";current.step="";saveState(current);queueAssistant({key:"contactSaved",payload:{kind:"contact"}},500);}}
  function conversationSummary(){return history().slice(-30).map(function(message){return (message.role==="user"?t("chatbot.customerLabel"):t("chatbot.assistantLabel"))+": "+messageText(message);}).join("\n");}
  function copySummary(){var text=conversationSummary(),done=function(success){if(success){window.ELORA.App.toast(t("chatbot.copied"),"copy");return;}var box=document.createElement("textarea");box.className="concierge-copy-box";box.readOnly=true;box.value=text;messagesNode.appendChild(box);box.focus();box.select();scrollLatest();queueAssistant({key:"contactCopy"},300);};if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(text).then(function(){done(true);}).catch(function(){done(false);});}else{var temp=document.createElement("textarea");temp.value=text;temp.setAttribute("readonly","");temp.style.position="fixed";temp.style.opacity="0";document.body.appendChild(temp);temp.select();var success=false;try{success=document.execCommand("copy");}catch(e){}temp.remove();done(success);}}

  function respondToIntent(text){var current=state();if(current.mode==="tracking"){handleTrackingNumber(text);return;}if(current.mode==="size"){handleSizeQuery(text);return;}if(current.mode==="contact"){handleContact(text);return;}if(current.mode==="finder"){handleFinderText(text);return;}if(current.mode==="search"){current.mode="idle";current.step="";current.pendingQuery=text;saveState(current);showProducts(searchProducts(text,false),"productIntro");return;}
    var detected=intentScores(text),intent=detected.intent,product=currentProduct();if(detected.confidence<.3){queueAssistant({key:"unknown",payload:{kind:"actions",actions:unknownActions()}},460);return;}
    if(intent==="greeting")queueAssistant({key:"greeting",payload:{kind:"actions",actions:starterActions()}},420);
    else if(intent==="thanks")queueAssistant({key:"thanks"},350);
    else if(intent==="restart_conversation")newConversation();
    else if(intent==="product_recommendation")startFinder();
    else if(["product_search","category_search","budget_search","color_search"].indexOf(intent)>-1){current.pendingQuery=text;saveState(current);showProducts(searchProducts(text,false),"productIntro");}
    else if(intent==="size_help")startSize();
    else if(intent==="product_availability")queueAssistant({key:"availability",payload:product?{kind:"products",ids:[product.id]}:null},440);
    else if(intent==="add_to_cart"){if(product)showProducts([product],"productIntro");else if(current.lastProductIds&&current.lastProductIds.length)showProducts(current.lastProductIds.map(productById).filter(Boolean),"productIntro");else queueAssistant({key:"searchAsk"},420);}
    else if(intent==="add_to_wishlist"){if(product){var added=window.ELORA.store.toggleWishlist(product.id);queueAssistant({key:added?"addedWishlist":"removedWishlist"},360);}else queueAssistant({key:"searchAsk"},420);}
    else if(intent==="cart_help")queueAssistant({key:"cart",payload:{kind:"actions",actions:[{labelKey:"nav.cart",value:"navigate:#/cart"}]}},420);
    else if(intent==="checkout_help")queueAssistant({key:"checkout",payload:{kind:"actions",actions:[{labelKey:"cart.checkout",value:"navigate:#/checkout"}]}},440);
    else if(intent==="no_online_payment")queueAssistant({key:"payment"},420);
    else if(intent==="shipping_question")queueAssistant({key:"shipping"},420);
    else if(intent==="return_question")queueAssistant({key:"returns",payload:{kind:"return"}},440);
    else if(intent==="exchange_question")queueAssistant({key:"exchange",payload:{kind:"return"}},440);
    else if(intent==="order_tracking"||intent==="order_status")startTracking();
    else if(intent==="shein_request")queueAssistant({key:"shein",payload:{kind:"shein"}},440);
    else if(intent==="contact_team")startContact();
    else queueAssistant({key:"unknown",payload:{kind:"actions",actions:unknownActions()}},460);
  }
  function submitMessage(text){text=String(text==null?(inputNode&&inputNode.value||""):text).trim();if(!text){if(inputNode)inputNode.focus();return;}if(text.length>MAX_LENGTH){window.ELORA.App.toast(t("chatbot.tooLong"),"circle-alert");return;}if(hasSensitiveData(text)){if(inputNode)inputNode.value="";queueAssistant({key:"sensitiveWarning"},320);updateCounter();return;}addUser(text);if(inputNode){inputNode.value="";inputNode.style.height="auto";}updateCounter();respondToIntent(text);}

  function handleQuickAction(value,label){if(!value)return;if(value.indexOf("navigate:")===0){addUser(label);window.ELORA.Router.navigate(value.slice(9).replace(/^#/,""));closeChat();return;}if(value==="navigate-shein"){addUser(label);var query=state().pendingQuery||"";window.ELORA.Router.navigate("/request-from-shein"+(query?"?chatQuery="+encodeURIComponent(query):""));closeChat();return;}if(value==="contact-whatsapp"){addUser(label);var number=String((window.ELORA_CONFIG||{}).whatsappNumber||"").replace(/[^\d]/g,""),win=window.open("https://wa.me/"+number+"?text="+encodeURIComponent(conversationSummary()),"_blank","noopener,noreferrer");if(win)win.opener=null;return;}if(value==="contact-email"){addUser(label);location.href="mailto:"+encodeURIComponent((window.ELORA_CONFIG||{}).contactEmail||"")+"?subject="+encodeURIComponent(t("chatbot.emailSubject"))+"&body="+encodeURIComponent(conversationSummary());return;}if(value.indexOf("finder-")===0){addUser(label);handleFinderAction(value);return;}addUser(label);if(value==="start-finder")startFinder();else if(value==="ask-search"){var current=state();current.mode="search";current.step="query";saveState(current);queueAssistant({key:"searchAsk"},380);}else if(value==="start-size")startSize();else if(value==="start-tracking")startTracking();else if(value==="shein-info")queueAssistant({key:"shein",payload:{kind:"shein"}},420);else if(value==="policies"){queueAssistant({key:"shipping"},350);queueAssistant({key:"returns",payload:{kind:"return"}},350);}else if(value==="start-contact")startContact();else if(value==="alternatives"){var query=state().pendingQuery||"";showProducts(searchProducts(query,true),"productIntro");}else if(value==="show-more"){var currentState=state(),ids=currentState.lastProductIds||[],start=currentState.resultOffset||3,next=ids.slice(start,start+3);currentState.resultOffset=start+3;saveState(currentState);queueAssistant({text:"",payload:{kind:"products",ids:next,hasMore:currentState.resultOffset<ids.length}},350);}else if(value==="copy-summary")copySummary();}
  function handleProductAction(button){var card=button.closest("[data-chat-product]"),product=card&&productById(card.dataset.chatProduct);if(!product)return;var action=button.dataset.chatProductAction;if(action==="view"){window.ELORA.Router.navigate("/product/"+product.id);closeChat();return;}if(action==="add"){var select=card.querySelector("[data-chat-size]"),swatch=card.querySelector("[data-chat-color].is-active");window.ELORA.store.addToCart(product.id,1,select?select.value:(product.sizes[0]||"ONE"),swatch?swatch.dataset.chatColor:(product.colors[0]||""));button.classList.add("is-success");button.textContent=t("shop.added");window.ELORA.App.toast(t("shop.added"),"shopping-bag");queueAssistant({key:"addedCart"},320);return;}if(action==="wishlist"){var added=window.ELORA.store.toggleWishlist(product.id);button.classList.toggle("is-active",added);button.setAttribute("aria-label",t(added?"chatbot.removeWishlist":"chatbot.wishlist"));window.ELORA.App.toast(copy(added?"addedWishlist":"removedWishlist"),"heart");}}
  function updateCounter(){if(!inputNode||!counterNode)return;var length=inputNode.value.length,remaining=MAX_LENGTH-length;counterNode.hidden=length<MAX_LENGTH-100;counterNode.textContent=remaining+" "+t("chatbot.characterCount");inputNode.style.height="auto";inputNode.style.height=Math.min(inputNode.scrollHeight,120)+"px";}

  function nudgeCopy(){var path=route().path,key=path.indexOf("/product/")===0?"product":path==="/shop"?"shop":path==="/cart"?"cart":path.indexOf("/search")===0?"search":path.indexOf("/tracking")===0?"tracking":path.indexOf("/returns")===0?"returns":path==="/home"||path==="/"?"home":"default";return pick(DATA.copy.proactive[key]||DATA.copy.proactive.default);}
  function hideNudge(mark){if(nudgeNode)nudgeNode.hidden=true;if(mark)safeStorage(sessionStorage,"elora_chat_nudge_dismissed","1");}
  function showNudge(){if(!nudgeNode||open||route().path==="/checkout"||document.body.classList.contains("is-locked")||safeStorage(sessionStorage,"elora_chat_nudge_dismissed"))return;var text=nudgeNode.querySelector("[data-chat-nudge-text]");if(text)text.textContent=nudgeCopy();nudgeNode.hidden=false;safeStorage(sessionStorage,"elora_chat_nudge_shown","1");}
  function scheduleNudge(){clearTimeout(proactiveTimer);if(safeStorage(sessionStorage,"elora_chat_nudge_shown")||safeStorage(sessionStorage,"elora_chat_nudge_dismissed")||route().path==="/checkout")return;proactiveTimer=setTimeout(showNudge,9000);}
  function onRouteChange(){if(!initialized)return;if(root)root.dataset.chatRoute=route().path;hideNudge(false);scheduleNudge();}
  function onLanguageChange(){if(!initialized)return;var wasOpen=open;buildShell();setOpenState(wasOpen,false);}

  function trapFocus(event){if(!open||event.key!=="Tab"||!panel)return;var focusable=Array.prototype.slice.call(panel.querySelectorAll('button:not([disabled]),a[href],textarea:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')).filter(function(node){return node.offsetParent!==null;}),first=focusable[0],last=focusable[focusable.length-1];if(!first)return;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
  function bindEvents(){root.addEventListener("click",function(event){var command=event.target.closest("[data-chat-command]"),quick=event.target.closest("[data-chat-action]"),productAction=event.target.closest("[data-chat-product-action]"),swatch=event.target.closest("[data-chat-color]");if(command){var value=command.dataset.chatCommand;if(value==="toggle")setOpenState(!open,true);else if(value==="open")openChat();else if(value==="close"||value==="minimize")closeChat();else if(value==="new")newConversation();else if(value==="send")submitMessage();else if(value==="latest")scrollLatest();else if(value==="dismiss-nudge")hideNudge(true);}if(quick)handleQuickAction(quick.dataset.chatAction,quick.textContent.trim());if(productAction)handleProductAction(productAction);if(swatch){var card=swatch.closest("[data-chat-product]");if(card)card.querySelectorAll("[data-chat-color]").forEach(function(node){node.classList.toggle("is-active",node===swatch);});}});
    root.addEventListener("input",function(event){if(event.target.matches("[data-chat-input]"))updateCounter();});
    root.addEventListener("keydown",function(event){if(event.target.matches("[data-chat-input]")&&event.key==="Enter"&&!event.shiftKey){event.preventDefault();submitMessage();return;}if(event.key==="Escape"&&open){event.preventDefault();closeChat();return;}trapFocus(event);});
    root.addEventListener("scroll",function(event){if(event.target===messagesNode&&latestButton)latestButton.hidden=nearBottom();},true);
    document.addEventListener("elora:language",onLanguageChange);
  }
  function init(){if(initialized)return;initialized=true;root=document.createElement("div");root.className="elora-concierge";root.setAttribute("data-elora-concierge","");root.dataset.chatRoute=route().path;document.body.appendChild(root);initSearch();buildShell();bindEvents();if(!history().length){addAssistant({key:"welcome",payload:{kind:"actions",actions:starterActions()}});window.ELORA.store.setChatUnread(0);updateUnread();}renderHistory(false);scheduleNudge();}

  window.ELORA.Chatbot={init:init,open:openChat,close:closeChat,onRouteChange:onRouteChange,onLanguageChange:onLanguageChange,detectIntent:intentScores,search:searchProducts,normalize:normalize};
})();
