(function () {
  "use strict";
  window.ELORA = window.ELORA || {};
  function t(key) { return window.ELORA.I18N.t(key); }
  function pick(value) { return window.ELORA.I18N.pick(value); }
  function escapeHTML(value) { return String(value == null ? "" : value).replace(/[&<>'"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c]; }); }
  function money(value) { var ar = window.ELORA.I18N.language === "ar"; return new Intl.NumberFormat(ar ? "ar-EG" : "en-EG", { maximumFractionDigits: 0 }).format(value) + " " + (ar ? "ج.م" : "EGP"); }
  function date(value) { return new Intl.DateTimeFormat(window.ELORA.I18N.language === "ar" ? "ar-EG" : "en-EG", { year: "numeric", month: "short", day: "numeric" }).format(new Date(value)); }
  function categoryById(id) { return window.ELORA_DATA.categories.find(function (category) { return category.id === id; }); }
  function subcategoryById(categoryId, id) { var category=categoryById(categoryId); return category && category.subcategories ? category.subcategories.find(function (subcategory) { return subcategory.id === id; }) : null; }
  function categoryLabel(id) { var category=categoryById(id); return category ? pick(category.name) : ""; }
  function subcategoryLabel(categoryId, id) { var subcategory=subcategoryById(categoryId,id); return subcategory ? pick(subcategory.name) : ""; }
  function icon(name, label) { return '<i class="icon" data-lucide="' + name + '"' + (label ? ' aria-label="' + escapeHTML(label) + '"' : ' aria-hidden="true"') + '></i>'; }
  function navLink(route, key) { var current = (location.hash || "#/home").replace(/^#/, ""); return '<a href="#' + route + '"' + (current === route || current.indexOf(route + "&") === 0 ? ' aria-current="page"' : "") + '>' + t(key) + "</a>"; }
  function header() {
    var count = window.ELORA.store ? window.ELORA.store.cartCount() : 0;
    var wishes = window.ELORA.store ? window.ELORA.store.state.wishlist.length : 0;
    var onCart = (location.hash || "#/home").replace(/^#/, "").split("?")[0] === "/cart";
    return '<header class="site-header" data-header><div class="container header-row">' +
      '<button class="icon-btn mobile-only" data-action="open-menu" aria-label="' + t("nav.menu") + '">' + icon("menu") + '</button>' +
      '<a class="brand" href="#/home" aria-label="ÉLORA"><span class="brand__name">ÉLORA</span><span class="brand__tag">' + t("brand.tagline") + '</span></a>' +
      '<nav class="desktop-nav" aria-label="' + t("nav.primary") + '">' + navLink("/shop?category=new-in", "nav.newIn") + navLink("/shop?category=fashion", "nav.fashion") + navLink("/shop?category=bags-shoes", "nav.bagsShoes") + navLink("/shop?category=accessories-beauty", "nav.accessoriesBeauty") + navLink("/request-from-shein", "nav.requestShein") + '</nav>' +
      '<div class="header-actions"><button class="lang-btn" data-action="toggle-language" aria-label="' + t("nav.language") + '">' + t("nav.language") + '</button><button class="icon-btn desktop-only" data-action="open-search" aria-label="' + t("nav.search") + '">' + icon("search") + '</button><a class="icon-btn relative desktop-only" href="#/wishlist" aria-label="' + t("nav.wishlist") + '">' + icon("heart") + (wishes ? '<span class="count">' + wishes + '</span>' : "") + '</a><button class="icon-btn relative cart-button' + (onCart ? ' is-current' : '') + '" type="button" data-action="open-mini-cart" aria-label="' + t("nav.cart") + '"' + (onCart ? ' aria-current="page"' : '') + '>' + icon("shopping-bag") + '<span class="count" data-cart-count' + (count ? "" : " hidden") + '>' + count + '</span></button><a class="icon-btn desktop-only" href="#/account" aria-label="' + t("nav.account") + '">' + icon("user") + "</a></div></div></header>";
  }
  function mobileMenu() { return '<div class="scrim" data-scrim data-action="close-overlays"></div><aside class="mobile-nav" data-mobile-menu aria-label="' + t("nav.menu") + '"><div class="cluster" style="justify-content:space-between"><span class="brand__name">ÉLORA</span><button class="icon-btn" data-action="close-overlays" aria-label="' + t("nav.closeMenu") + '">' + icon("x") + '</button></div><nav class="mobile-nav__links">' + navLink("/shop?category=new-in", "nav.newIn") + navLink("/shop?category=fashion", "nav.fashion") + navLink("/shop?category=bags-shoes", "nav.bagsShoes") + navLink("/shop?category=accessories-beauty", "nav.accessoriesBeauty") + navLink("/request-from-shein", "nav.requestShein") + '</nav><div class="footer-links" style="margin-bottom:1.5rem"><a href="#/wishlist">' + t("nav.wishlist") + '</a><a href="#/cart">' + t("nav.cart") + '</a><a href="#/account">' + t("nav.account") + '</a></div><div class="stack"><button class="btn btn--secondary" data-action="open-search">' + icon("search") + t("nav.search") + '</button><button class="btn btn--ghost" data-action="toggle-language">AR | EN</button></div></aside>';
  }
  function searchOverlay() { return '<section class="search-overlay" data-search-overlay aria-label="' + t("search.title") + '"><div class="search-head"><input class="input search-input" data-search-input aria-label="' + t("search.title") + '" placeholder="' + t("search.placeholder") + '"><button class="icon-btn" data-action="close-overlays" aria-label="' + t("common.close") + '">' + icon("x") + '</button></div><div class="search-results" data-search-results></div></section>';
  }
  function footer() { return '<footer class="site-footer" data-reveal="footer"><div class="container"><div class="footer-monogram" aria-hidden="true">É</div><div class="footer-grid"><div data-reveal="split"><a class="brand" href="#/home"><span class="brand__name">ÉLORA</span><span class="brand__tag">' + t("brand.tagline") + '</span></a><p style="margin-top:1.25rem;max-width:38ch">' + t("footer.story") + '</p></div><div data-reveal="stagger"><div class="footer-title">' + t("footer.shop") + '</div><div class="footer-links"><a href="#/shop?category=new-in">' + t("footer.newIn") + '</a><a href="#/shop?category=fashion">' + t("footer.fashion") + '</a><a href="#/shop?category=bags-shoes">' + t("footer.bagsShoes") + '</a><a href="#/shop?category=accessories-beauty">' + t("footer.accessoriesBeauty") + '</a><a href="#/request-from-shein">' + t("footer.requestShein") + '</a></div></div><div data-reveal="stagger"><div class="footer-title">' + t("footer.help") + '</div><div class="footer-links"><a href="#/checkout">' + t("footer.delivery") + '</a><a href="#/returns">' + t("footer.exchange") + '</a><a href="#/tracking">' + t("footer.track") + '</a></div></div><div data-reveal="stagger"><div class="footer-title">' + t("footer.follow") + '</div><div class="footer-links"><a href="#/home">' + t("footer.instagram") + '</a><a href="#/home">' + t("footer.tiktok") + '</a><a href="#/home">' + t("footer.whatsapp") + '</a><a href="#/home">' + t("footer.pinterest") + '</a></div></div></div><div class="footer-bottom"><span>' + t("footer.rights") + '</span><span>' + t("footer.privacy") + "</span></div></div></footer>"; }
  function mobileBottomNav() { var path=(location.hash||"#/home").replace(/^#/,"").split("?")[0],active=function(paths){return paths.some(function(item){return item instanceof RegExp?item.test(path):item===path;});},item=function(href,key,iconName,paths){var current=active(paths);return '<a class="mobile-bottom-nav__item '+(current?"is-active":"")+'" href="'+href+'" aria-label="'+t(key)+'"'+(current?' aria-current="page"':"")+'>'+icon(iconName)+'<span>'+t(key)+'</span></a>';};return '<nav class="mobile-bottom-nav" aria-label="'+t("nav.primary")+'">'+item("#/home","nav.home","house",["/","/home"])+item("#/shop","nav.shop","layout-grid",["/shop","/product-listing",/^\/product\//])+ '<button class="mobile-bottom-nav__item '+(active(["/search","/smart-search"])?"is-active":"")+'" type="button" data-action="open-search" aria-label="'+t("nav.search")+'">'+icon("search")+'<span>'+t("nav.search")+'</span></button>'+item("#/wishlist","nav.wishlist","heart",["/wishlist"])+item("#/account","nav.account","user",["/account","/addresses","/orders","/returns",/^\/addresses\//,/^\/orders\//,/^\/returns\//])+'</nav>'; }
  function shell(content) { return header() + mobileMenu() + searchOverlay() + '<main id="main-content" class="page-transition">' + content + "</main>" + footer() + mobileBottomNav(); }
  function productImage(product, index, extra, eager) {
    var images=product&&Array.isArray(product.images)?product.images:[], src=images[index||0];
    if(!src) return '<div class="product-art product-art--fallback ' + (extra || "") + '" style="--dress:' + product.art + '" aria-hidden="true"></div>';
    return '<img class="product-image ' + (extra||"") + '" src="' + escapeHTML(src) + '" alt="' + escapeHTML(pick(product.name)) + '" width="900" height="1200" loading="' + (eager?"eager":"lazy") + '" decoding="async" style="object-position:' + escapeHTML(product.imagePosition||"center") + '">';
  }
  function productArt(product, extra) { return '<div class="product-art ' + (extra || "") + '" style="--dress:' + product.art + '">' + productImage(product,0,"product-art__image") + '</div>'; }
  function productCard(product) {
    var wished = window.ELORA.store && window.ELORA.store.isWishlisted(product.id);
    var badge = product.badge ? '<span class="badge">' + t("shop." + (product.badge === "best" ? "newest" : product.badge === "limited" ? "filterTitle" : "newest")) + '</span>' : "";
    return '<article class="product-card card" data-product-card data-id="' + product.id + '" data-reveal="product"><div class="product-card__media">' + badge + '<button class="wishlist-btn ' + (wished ? "is-active" : "") + '" data-action="toggle-wishlist" data-id="' + product.id + '" aria-label="' + t("nav.wishlist") + '">' + icon("heart") + '</button><a class="product-card__image-link" href="#/product/' + product.id + '" aria-label="' + escapeHTML(pick(product.name)) + '">' + productImage(product,0,"product-card__image product-card__image--primary") + (product.images&&product.images[1]?productImage(product,1,"product-card__image product-card__image--secondary"):"") + '</a><button class="btn btn--secondary quick-view" data-action="quick-view" data-id="' + product.id + '">' + t("shop.quickView") + '</button></div><div class="product-card__body"><p class="eyebrow" style="margin-bottom:.35rem">' + escapeHTML(subcategoryLabel(product.category,product.subcategory) || categoryLabel(product.category)) + '</p><a class="product-card__title" href="#/product/' + product.id + '">' + escapeHTML(pick(product.name)) + '</a><div class="product-card__meta"><strong>' + money(product.price) + '</strong><span class="swatches">' + product.colors.map(function (c) { return '<span class="swatch" style="background:' + c + '"></span>'; }).join("") + "</span></div></div></article>";
  }
  function breadcrumb(items) { return '<nav class="breadcrumb" aria-label="Breadcrumb">' + items.map(function (item, i) { var part = item.href ? '<a href="' + item.href + '">' + escapeHTML(item.label) + '</a>' : '<span>' + escapeHTML(item.label) + '</span>'; return part + (i < items.length - 1 ? icon("chevron-right") : ""); }).join("") + "</nav>"; }
  function pageHero(eyebrow, title, body) { return '<section class="page-hero"><div class="container page-hero__inner" data-reveal><p class="eyebrow">' + eyebrow + '</p><h1 class="page-title">' + title + '</h1>' + (body ? '<p class="lead">' + body + '</p>' : "") + "</div></section>"; }
  function emptyState(iconName, title, body, buttonLabel, href) { return '<div class="empty-state" data-reveal><div class="empty-state__icon">' + icon(iconName) + '</div><h2>' + title + '</h2><p>' + body + '</p>' + (buttonLabel ? '<a class="btn btn--primary" href="' + (href || "#/shop") + '">' + buttonLabel + "</a>" : "") + "</div>"; }
  function sheinCta(extraClass) { return '<aside class="shein-cta ' + (extraClass || "") + '" data-reveal><div class="shein-cta__mark">' + icon("sparkles") + '</div><div><p class="eyebrow">SHEIN × ÉLORA</p><h2>' + t("shein.ctaTitle") + '</h2><p>' + t("shein.ctaBody") + '</p></div><a class="btn btn--primary" href="#/request-from-shein">' + t("shein.ctaButton") + icon("arrow-right") + '</a></aside>'; }
  function summary(subtotal) { var discount = window.ELORA.store.state.promo ? subtotal * .1 : 0, total = subtotal - discount; return '<aside class="summary card"><h3>' + t("cart.total") + '</h3><div class="summary-row"><span>' + t("cart.subtotal") + '</span><strong>' + money(subtotal) + '</strong></div>' + (discount ? '<div class="summary-row"><span>ELORA10</span><strong>−' + money(discount) + '</strong></div>' : "") + '<div class="summary-row"><span>' + t("cart.delivery") + '</span><strong>' + t("cart.free") + '</strong></div><div class="summary-row summary-row--total"><span>' + t("cart.total") + '</span><strong>' + money(total) + '</strong></div></aside>'; }
  window.ELORA.Components = { t:t,pick:pick,escape:escapeHTML,money:money,date:date,icon:icon,shell:shell,productImage:productImage,productArt:productArt,productCard:productCard,breadcrumb:breadcrumb,pageHero:pageHero,emptyState:emptyState,sheinCta:sheinCta,summary:summary,categoryById:categoryById,subcategoryById:subcategoryById,categoryLabel:categoryLabel,subcategoryLabel:subcategoryLabel };
})();
