(function () {
  "use strict";
  window.ELORA = window.ELORA || {};
  window.ELORA_I18N = {
    en: {
      meta: { title: "ÉLORA — Women's Fashion, Beauty & Accessories" },
      common: { shopNow: "Shop now", discover: "Discover", continue: "Continue", back: "Back", save: "Save", cancel: "Cancel", close: "Close", remove: "Remove", edit: "Edit", add: "Add", submit: "Submit", retry: "Try again", viewDetails: "View details", learnMore: "Learn more", required: "This field is required", invalidEmail: "Enter a valid email address", loading: "Loading", success: "Success", error: "Something went wrong", items: "items", currency: "EGP", yes: "Yes", no: "No" },
      brand: { tagline: "CURATED FOR HER" },
      nav: { home: "Home", shop: "Shop", newIn: "New In", fashion: "Fashion", bagsShoes: "Bags & Shoes", accessoriesBeauty: "Accessories & Beauty", requestShein: "Request from SHEIN", wishlist: "Wishlist", cart: "Bag", account: "My account", search: "Search", menu: "Open menu", closeMenu: "Close menu", language: "العربية", primary: "Primary navigation" },
      categories: { newIn: "New In", fashion: "Fashion", dresses: "Dresses", tops: "Tops", bottoms: "Bottoms", sets: "Sets", jackets: "Jackets", bagsShoes: "Bags & Shoes", handbags: "Handbags", shoulderBags: "Shoulder Bags", heels: "Heels", flats: "Flats", sneakers: "Sneakers", accessoriesBeauty: "Accessories & Beauty", jewelry: "Jewelry", watches: "Watches", sunglasses: "Sunglasses", hairAccessories: "Hair Accessories", beauty: "Beauty", skincare: "Skincare" },
      announcement: "Delivery timing and available service options are confirmed when your order is reviewed.",
      home: { eyebrow: "THE ÉLORA EDIT", title: "Every detail, distinctly yours.", body: "A curated world of fashion, bags, shoes, accessories, beauty and skincare selected for every part of your day.", styleQuiz: "Find my edit", trust: "Considered style • Personal guidance • Easy exchange", moments: "The departments", momentsTitle: "A world selected around you", new: "Just landed", newTitle: "New arrivals, quietly exceptional", look: "Complete the edit", lookTitle: "One look. Every detail considered.", lookBody: "Explore the dress, bag and finishing accessories — or add the complete edit in one step.", quiz: "Your personal edit", quizTitle: "What are you shopping for?", quizBody: "Answer four quick questions and get a curated selection that matches your style, needs and color preferences.", quizEveryday: "Everyday ease", quizWork: "Work & meetings", quizEvents: "Dinner & events", community: "The ÉLORA journal", communityTitle: "Details worth noticing", heroNote: "AUTUMN / WINTER 2026", scroll: "Scroll to explore", marquee: "CURATED FASHION • BAGS • SHOES • ACCESSORIES • BEAUTY", editorialEyebrow: "Modern femininity", editorialTitle: "Made for the rhythm of her day", editorialBody: "Soft structure, rich texture and versatile pieces designed to move effortlessly from morning to evening.", accessoriesTitle: "The finishing touch", accessoriesBody: "Jewelry, eyewear and beauty essentials that make the look entirely your own.", shopLook: "Shop the look", shopLookHint: "Select a detail to explore it", lookPointDress: "The satin dress", lookPointBag: "The structured bag", lookPointJewelry: "The gold detail", viewCollection: "View collection", imageCredit: "Editorial imagery" },
      shop: { eyebrow: "THE COLLECTION", title: "Made to feel like you", body: "Discover fashion, bags, shoes, accessories and beauty selected for your everyday.", sectionBody: "Explore a curated selection from this ÉLORA department.", filters: "Filters", sort: "Sort", newest: "Newest", priceLow: "Price: low to high", priceHigh: "Price: high to low", category: "Department", subcategory: "Category", size: "Size", price: "Price", clear: "Clear filters", results: "products found", quickView: "Quick view", addCart: "Add to bag", added: "Added to your bag", wishlistAdded: "Saved to your wishlist", wishlistRemoved: "Removed from wishlist", filterTitle: "Refine your edit" },
      product: { color: "Color", size: "Select size", guide: "Size guide", assistant: "Find my size", quantity: "Quantity", details: "Product details", delivery: "Delivery & returns", care: "Care guide", selectSize: "Please select a size", recently: "You may also love", zoom: "Zoom product image", imageOf: "Product image", closeGallery: "Close gallery", previousImage: "Previous image", nextImage: "Next image" },
      search: { title: "Smart search", placeholder: "Search fashion, bags, shoes, beauty…", recent: "Recent searches", suggestions: "Explore departments", noResults: "No matching products found", viewAll: "View all results", clear: "Clear recent searches", emptyCtaTitle: "Can’t find what you’re looking for?", emptyCtaBody: "Send us the SHEIN product and we’ll help you order it.", emptyCtaButton: "Request from SHEIN" },
      wishlist: { title: "Your wishlist", body: "A quiet place for the pieces you love.", emptyTitle: "Your wishlist is waiting", emptyBody: "Save pieces with the heart icon and find them here." },
      cart: { title: "Your bag", body: "Review your selection before submitting it.", emptyTitle: "Your bag is empty", emptyBody: "Discover something made for your next moment.", regularItems: "ÉLORA products", specialItems: "SHEIN special requests", subtotal: "Current subtotal", delivery: "Delivery", total: "Current total", checkout: "Continue to request review", promo: "Promo code", apply: "Apply", promoSuccess: "ELORA10 applied — 10% off", free: "Confirmed after review", updateQty: "Update quantity", excludesSpecial: "The current total excludes special requests that are still under review." },
      checkout: { title: "Submit your order", contact: "Customer details", delivery: "Delivery address", review: "Review your request", email: "Email address", firstName: "First name", lastName: "Last name", phone: "Phone number", address: "Delivery address", city: "Governorate / region", area: "Area", addressDetails: "Additional address details", notes: "Order notes", terms: "I confirm that my details are correct and agree to have this order reviewed.", placeOrder: "Submit Order for Review", notice: "No payment is collected on the website. After reviewing availability and pricing, the ÉLORA team will contact you to confirm the order and payment method.", orderPlaced: "Your order was submitted for review", demoNotice: "This is a local demo. The request has been saved on this device and has not been sent to a live store system.", regularReview: "ÉLORA products", specialReview: "SHEIN special requests" },
      auth: { welcome: "Welcome back", loginBody: "Sign in to view orders, addresses and your saved edit.", email: "Email address", password: "Password", showPassword: "Show password", hidePassword: "Hide password", forgot: "Forgot password?", login: "Sign in", noAccount: "New to ÉLORA?", register: "Create account", createTitle: "Create your ÉLORA account", createBody: "Save your edit and make checkout beautifully simple.", name: "Full name", confirmPassword: "Confirm password", haveAccount: "Already have an account?", otpTitle: "Verify your email", otpBody: "Enter the 6-digit code sent to your email.", verify: "Verify code", resend: "Resend code", resendIn: "Resend in", forgotTitle: "Reset your password", forgotBody: "We will send a secure reset link to your email.", sendLink: "Send reset link", resetTitle: "Choose a new password", newPassword: "New password", reset: "Reset password", resetSuccessTitle: "Password reset", resetSuccessBody: "Your password was changed successfully. You can now sign in.", loginError: "The email or password is incorrect.", otpInvalid: "The verification code is invalid.", otpExpired: "The verification code has expired." },
      account: { title: "My account", overview: "Overview", addresses: "Saved addresses", orders: "Orders", returns: "Returns", sheinRequests: "SHEIN Special Requests", logout: "Sign out", hello: "Hello, Mariam", helloBody: "Manage your details, orders and saved addresses.", activeOrders: "Active orders", savedPieces: "Saved pieces", addressCount: "Addresses", recentOrder: "Recent order", addAddress: "Add new address", emptyAddress: "Your address book is empty", emptyAddressBody: "Add an address to make checkout faster.", primary: "Primary", label: "Address label", street: "Street address", building: "Building / apartment", setPrimary: "Set as primary address", noSheinRequests: "No submitted SHEIN requests yet.", viewRequest: "View details", cancelRequest: "Cancel request" },
      orders: { title: "Your orders", body: "Track current orders and revisit previous edits.", emptyTitle: "No orders yet", emptyBody: "Your order history will appear here after your first request.", order: "Order", placed: "Submitted", status: "Status", track: "Track request", delivered: "Delivered", in_transit: "In transit", cancelled: "Cancelled", delayed: "Delayed", confirmed: "Order Confirmed", packed: "Packed", shipped: "Shipped", pending_review: "Pending Review", reviewing: "Reviewing Product", price_confirmed: "Price Confirmed", awaiting_customer_confirmation: "Awaiting Customer Confirmation", ordered_from_supplier: "Ordered from Supplier", arrived_at_warehouse: "Arrived at Warehouse", out_for_delivery: "Out for Delivery", unavailable: "Product Unavailable", deliveredTitle: "Your order was delivered", cancelledTitle: "This order was cancelled", delayedTitle: "Your order is running late", trackingTitle: "Track your request", trackingBody: "Review and fulfilment progress", confirmationTitle: "Your request has been received", confirmationBody: "Our team will review the products, availability, and pricing, then contact you to confirm the details and payment method.", confirmationPending: "This request is not finally confirmed until the ÉLORA team contacts you.", followRequest: "Follow request", backShopping: "Back to shopping", summary: "Request summary" },
      shein: { eyebrow: "ÉLORA SPECIAL REQUEST", title: "Request your favorite SHEIN item", intro: "Paste the product link, choose your options, and we’ll review availability and the final price before confirming your order.", finalPriceNote: "The final price is confirmed only after review.", ctaTitle: "Can’t find what you’re looking for?", ctaBody: "Send us the SHEIN product and we’ll help you order it.", ctaButton: "Request from SHEIN", howTitle: "How it works", steps: ["Copy the product link from SHEIN.","Select the color, size, and quantity.","Submit the request for review.","We review availability and pricing.","We contact you to confirm the order and payment method."], formTitle: "Product request details", productUrl: "SHEIN product link", urlPlaceholder: "Paste the SHEIN product link here", productName: "Product name", productNamePlaceholder: "Enter the product name manually (optional)", optional: "Optional", image: "Product image", upload: "Upload an image or screenshot", uploadHint: "Optional, but it helps us review your request. JPG, PNG or WebP.", previewAlt: "Preview of the selected product image", removeImage: "Remove image", color: "Requested color", colorPlaceholder: "Enter the color exactly as shown", size: "Requested size", chooseSize: "Choose a size", sheinSizeText: "Size written on the SHEIN page", sheinSizePlaceholder: "Optional size wording or measurements", quantity: "Quantity", decreaseQuantity: "Decrease quantity", increaseQuantity: "Increase quantity", displayedPrice: "Price shown on SHEIN", displayedPriceNote: "Optional reference only. It is not the final price and may change.", displayedCurrency: "Displayed currency", otherCurrency: "Other", notes: "Additional notes", notesPlaceholder: "Color variant link, measurements, or any useful details", consent: "I understand that the final price, availability, and delivery estimate will be confirmed after review.", addToCart: "Add Request to Cart", updateCart: "Update Request", invalidUrl: "Please enter a valid SHEIN product link.", imageError: "Please choose a JPG, PNG or WebP image.", imageTooLarge: "The image could not be saved. Please choose a smaller image.", added: "Special request added to your bag", updated: "Special request updated", specialBadge: "Special SHEIN Request", fallbackName: "SHEIN Product Request", openLink: "Open Product Link", pricePending: "Price Pending Review", availabilityPending: "Availability Pending", editRequest: "Edit request", pendingNotice: "Price, availability and delivery timing will be confirmed after review.", displayedPriceLabel: "Price entered by you", finalPrice: "Final price", notSet: "Not set", availability: "Availability", reviewStatus: "Review status", detailsTitle: "SHEIN request details", cancelSuccess: "The request was cancelled", cartEmptyCta: "You can also request an item from SHEIN.", demoSaved: "Saved locally on this device for demonstration." },
      returns: { title: "Returns & exchanges", body: "Simple steps, clear updates and support when you need it.", start: "Start a return", policy: "Return policy", requestTitle: "Return request", orderNumber: "Order number", reason: "Reason for return", reasonPlaceholder: "Choose a reason", fit: "Fit wasn't right", changed: "Changed my mind", damaged: "Item arrived damaged", other: "Other", details: "Tell us more", upload: "Upload a photo", uploadHint: "PNG or JPG up to 10 MB", submittedTitle: "Return request submitted", submittedBody: "We will review your request and email the next steps within one business day.", emptyTitle: "No returns", emptyBody: "Any active or previous return requests will appear here.", acceptedTitle: "Return accepted", acceptedBody: "Follow the instructions sent to your email to send the item back.", rejectedTitle: "Return not approved", rejectedBody: "This item is outside the return window. Contact support if you need help.", refundTitle: "Refund in progress", refundBody: "Your refund is being processed and should appear within 5–7 business days." },
      states: { loadingTitle: "Preparing your edit", loadingBody: "A few beautiful things are almost ready.", emptyTitle: "Nothing here yet", emptyBody: "Explore the collection to start your edit.", offlineTitle: "You appear to be offline", offlineBody: "Check your internet connection and try again. Your saved bag is still available.", notFoundTitle: "Page not found", notFoundBody: "The page you are looking for has moved or no longer exists.", successTitle: "Everything is ready", successBody: "Your changes have been saved successfully.", errorTitle: "We couldn't complete that", errorBody: "Please try again in a moment." },
      footer: { story: "Fashion, bags, shoes, accessories and beauty curated for every side of her.", shop: "Shop", help: "Help", follow: "Follow", newIn: "New In", fashion: "Fashion", bagsShoes: "Bags & Shoes", accessoriesBeauty: "Accessories & Beauty", requestShein: "Request from SHEIN", delivery: "Delivery", exchange: "Exchange policy", track: "Track order", instagram: "Instagram", tiktok: "TikTok", whatsapp: "WhatsApp", pinterest: "Pinterest", rights: "© 2026 ÉLORA. Built with care.", privacy: "Privacy • Terms • Returns" }
    },
    ar: {}
  };

  window.ELORA_I18N.ar = {
    meta:{title:"إيلورا — أزياء وجمال وإكسسوارات نسائية"},common:{shopNow:"تسوقي الآن",discover:"اكتشفي",continue:"متابعة",back:"رجوع",save:"حفظ",cancel:"إلغاء",close:"إغلاق",remove:"إزالة",edit:"تعديل",add:"إضافة",submit:"إرسال",retry:"حاولي مجددًا",viewDetails:"عرض التفاصيل",learnMore:"اعرفي المزيد",required:"هذا الحقل مطلوب",invalidEmail:"أدخلي بريدًا إلكترونيًا صحيحًا",loading:"جارٍ التحميل",success:"تم بنجاح",error:"حدث خطأ",items:"قطع",currency:"ج.م",yes:"نعم",no:"لا"},
    brand:{tagline:"منتقى لها"},
    nav:{home:"الرئيسية",shop:"المتجر",newIn:"وصل حديثًا",fashion:"أزياء",bagsShoes:"حقائب وأحذية",accessoriesBeauty:"إكسسوارات وجمال",requestShein:"اطلبي من SHEIN",wishlist:"المفضلة",cart:"الحقيبة",account:"حسابي",search:"بحث",menu:"فتح القائمة",closeMenu:"إغلاق القائمة",language:"English",primary:"القائمة الرئيسية"},
    categories:{newIn:"وصل حديثًا",fashion:"أزياء",dresses:"فساتين",tops:"بلوزات",bottoms:"بناطيل وتنانير",sets:"أطقم",jackets:"جاكيتات",bagsShoes:"حقائب وأحذية",handbags:"حقائب يد",shoulderBags:"حقائب كتف",heels:"أحذية بكعب",flats:"أحذية فلات",sneakers:"أحذية رياضية",accessoriesBeauty:"إكسسوارات وجمال",jewelry:"مجوهرات",watches:"ساعات",sunglasses:"نظارات شمسية",hairAccessories:"إكسسوارات الشعر",beauty:"مستحضرات تجميل",skincare:"العناية بالبشرة"},announcement:"يتم تأكيد موعد التوصيل وخيارات الخدمة المتاحة عند مراجعة طلبك.",
    home:{eyebrow:"اختيارات ÉLORA",title:"كل تفصيلة، تشبهكِ.",body:"عالم منتقى من الأزياء والحقائب والأحذية والإكسسوارات والجمال والعناية بالبشرة لكل تفاصيل يومك.",styleQuiz:"اكتشفي اختياراتك",trust:"ستايل مدروس • إرشاد شخصي • استبدال سهل",moments:"الأقسام",momentsTitle:"عالم مختار حولكِ",new:"وصل حديثًا",newTitle:"اختيارات جديدة بتفاصيل استثنائية",look:"أكملي الإطلالة",lookTitle:"إطلالة واحدة. كل تفصيلة محسوبة.",lookBody:"اكتشفي الفستان والحقيبة والإكسسوارات المكملة، أو أضيفي الاختيار كاملًا بخطوة واحدة.",quiz:"اختيارك الشخصي",quizTitle:"عمّ تبحثين اليوم؟",quizBody:"أجيبي عن أربعة أسئلة سريعة لنقدم لكِ اختيارات تناسب أسلوبك واحتياجاتك وألوانك.",quizEveryday:"إطلالة يومية",quizWork:"العمل والاجتماعات",quizEvents:"العشاء والمناسبات",community:"مجلة ÉLORA",communityTitle:"تفاصيل تستحق التأمل",heroNote:"خريف / شتاء ٢٠٢٦",scroll:"مرّري للاستكشاف",marquee:"أزياء منتقاة • حقائب • أحذية • إكسسوارات • جمال",editorialEyebrow:"أنوثة عصرية",editorialTitle:"مصممة لإيقاع يومها",editorialBody:"قصّات ناعمة وخامات غنية وقطع مرنة تنتقل بسهولة من الصباح إلى المساء.",accessoriesTitle:"اللمسة الأخيرة",accessoriesBody:"مجوهرات ونظارات وأساسيات جمال تجعل الإطلالة ملككِ بالكامل.",shopLook:"تسوقي الإطلالة",shopLookHint:"اختاري تفصيلة لاستكشافها",lookPointDress:"الفستان الساتان",lookPointBag:"الحقيبة المنظمة",lookPointJewelry:"التفصيلة الذهبية",viewCollection:"شاهدي المجموعة",imageCredit:"صور تحريرية"},
    shop:{eyebrow:"التشكيلة",title:"مختارة لتشبهك",body:"اكتشفي الأزياء والحقائب والأحذية والإكسسوارات والجمال المختارة ليومك.",sectionBody:"اكتشفي مجموعة منتقاة من هذا القسم في إيلورا.",filters:"الفلاتر",sort:"الترتيب",newest:"الأحدث",priceLow:"السعر: من الأقل",priceHigh:"السعر: من الأعلى",category:"القسم",subcategory:"التصنيف",size:"المقاس",price:"السعر",clear:"مسح الفلاتر",results:"منتجات",quickView:"عرض سريع",addCart:"أضيفي للحقيبة",added:"تمت الإضافة إلى حقيبتك",wishlistAdded:"تم الحفظ في المفضلة",wishlistRemoved:"تمت الإزالة من المفضلة",filterTitle:"خصصي اختياراتك"},
    product:{color:"اللون",size:"اختاري المقاس",guide:"دليل المقاسات",assistant:"ساعديني في المقاس",quantity:"الكمية",details:"تفاصيل المنتج",delivery:"التوصيل والاسترجاع",care:"العناية بالقطعة",selectSize:"اختاري المقاس أولًا",recently:"قد يعجبك أيضًا",zoom:"تكبير صورة المنتج",imageOf:"صورة المنتج",closeGallery:"إغلاق معرض الصور",previousImage:"الصورة السابقة",nextImage:"الصورة التالية"},
    search:{title:"البحث الذكي",placeholder:"ابحثي عن أزياء، حقائب، أحذية، جمال…",recent:"عمليات البحث الأخيرة",suggestions:"اكتشفي الأقسام",noResults:"لم نجد منتجات مطابقة",viewAll:"عرض كل النتائج",clear:"مسح البحث الأخير",emptyCtaTitle:"مش لاقية اللي بتدوري عليه؟",emptyCtaBody:"اطلبيه من SHEIN وإحنا نوفّرهولك.",emptyCtaButton:"اطلبي من SHEIN"},wishlist:{title:"قائمة مفضلاتك",body:"مكان هادئ للقطع التي أحببتِها.",emptyTitle:"قائمة مفضلاتك بانتظارك",emptyBody:"احفظي القطع من أيقونة القلب وستظهر هنا."},
    cart:{title:"حقيبتك",body:"راجعي اختياراتك قبل إرسال الطلب.",emptyTitle:"حقيبتك فارغة",emptyBody:"اكتشفي قطعة صُنعت للحظتك القادمة.",regularItems:"منتجات ÉLORA",specialItems:"طلبات SHEIN الخاصة",subtotal:"الإجمالي الحالي",delivery:"التوصيل",total:"الإجمالي الحالي",checkout:"متابعة إرسال الطلب للمراجعة",promo:"كود الخصم",apply:"تطبيق",promoSuccess:"تم تطبيق ELORA10 — خصم ١٠٪",free:"يُحدد بعد المراجعة",updateQty:"تعديل الكمية",excludesSpecial:"الإجمالي الحالي لا يشمل الطلبات الخاصة التي ما زالت قيد المراجعة."},
    checkout:{title:"إرسال الطلب",contact:"بيانات العميلة",delivery:"عنوان التوصيل",review:"مراجعة الطلب",email:"البريد الإلكتروني",firstName:"الاسم الأول",lastName:"اسم العائلة",phone:"رقم الهاتف",address:"عنوان التوصيل",city:"المحافظة أو المنطقة",area:"المنطقة",addressDetails:"تفاصيل إضافية للعنوان",notes:"ملاحظات الطلب",terms:"أؤكد أن بياناتي صحيحة وأوافق على مراجعة هذا الطلب.",placeOrder:"إرسال الطلب للمراجعة",notice:"لا يتم الدفع داخل الموقع. بعد مراجعة الطلب والسعر والتوفر، سيتواصل معك فريق ÉLORA لتأكيد الطلب وتوضيح طريقة الدفع.",orderPlaced:"تم إرسال طلبك للمراجعة",demoNotice:"هذه تجربة محلية. تم حفظ الطلب على هذا الجهاز ولم يتم إرساله إلى نظام متجر فعلي.",regularReview:"منتجات ÉLORA",specialReview:"طلبات SHEIN الخاصة"},
    auth:{welcome:"مرحبًا بعودتك",loginBody:"سجّلي الدخول لعرض طلباتك وعناوينك واختياراتك المحفوظة.",email:"البريد الإلكتروني",password:"كلمة المرور",showPassword:"إظهار كلمة المرور",hidePassword:"إخفاء كلمة المرور",forgot:"نسيت كلمة المرور؟",login:"تسجيل الدخول",noAccount:"جديدة على إيلورا؟",register:"إنشاء حساب",createTitle:"أنشئي حساب إيلورا",createBody:"احفظي اختياراتك واجعلي التسوق أسهل.",name:"الاسم بالكامل",confirmPassword:"تأكيد كلمة المرور",haveAccount:"لديك حساب بالفعل؟",otpTitle:"تأكيد بريدك",otpBody:"أدخلي الرمز المكون من ٦ أرقام المرسل لبريدك.",verify:"تأكيد الرمز",resend:"إعادة إرسال الرمز",resendIn:"إعادة الإرسال خلال",forgotTitle:"استعادة كلمة المرور",forgotBody:"سنرسل رابطًا آمنًا لإعادة التعيين إلى بريدك.",sendLink:"إرسال الرابط",resetTitle:"اختاري كلمة مرور جديدة",newPassword:"كلمة المرور الجديدة",reset:"تغيير كلمة المرور",resetSuccessTitle:"تم تغيير كلمة المرور",resetSuccessBody:"تم تغيير كلمة مرورك بنجاح. يمكنك الآن تسجيل الدخول.",loginError:"البريد الإلكتروني أو كلمة المرور غير صحيحة.",otpInvalid:"رمز التحقق غير صحيح.",otpExpired:"انتهت صلاحية رمز التحقق."},
    account:{title:"حسابي",overview:"نظرة عامة",addresses:"العناوين المحفوظة",orders:"الطلبات",returns:"الاسترجاع",sheinRequests:"طلبات SHEIN الخاصة",logout:"تسجيل الخروج",hello:"مرحبًا مريم",helloBody:"أديري بياناتك وطلباتك وعناوينك المحفوظة.",activeOrders:"طلبات نشطة",savedPieces:"قطع محفوظة",addressCount:"العناوين",recentOrder:"أحدث طلب",addAddress:"إضافة عنوان جديد",emptyAddress:"دفتر العناوين فارغ",emptyAddressBody:"أضيفي عنوانًا لإتمام الطلب بسرعة.",primary:"أساسي",label:"اسم العنوان",street:"عنوان الشارع",building:"المبنى / الشقة",setPrimary:"تعيين كعنوان أساسي",noSheinRequests:"لا توجد طلبات SHEIN مرسلة بعد.",viewRequest:"عرض التفاصيل",cancelRequest:"إلغاء الطلب"},
    orders:{title:"طلباتك",body:"تابعي طلباتك الحالية وراجعي اختياراتك السابقة.",emptyTitle:"لا توجد طلبات بعد",emptyBody:"سيظهر سجل طلباتك هنا بعد إرسال أول طلب.",order:"طلب",placed:"تاريخ الإرسال",status:"الحالة",track:"متابعة الطلب",delivered:"تم التسليم",in_transit:"في الطريق",cancelled:"تم إلغاء الطلب",delayed:"متأخر",confirmed:"تم تأكيد الطلب",packed:"تم التجهيز",shipped:"تم الشحن",pending_review:"بانتظار المراجعة",reviewing:"جاري مراجعة المنتج",price_confirmed:"تم تحديد السعر",awaiting_customer_confirmation:"بانتظار موافقة العميلة",ordered_from_supplier:"تم الطلب من المورد",arrived_at_warehouse:"وصل إلى المخزن",out_for_delivery:"خرج للتوصيل",unavailable:"المنتج غير متوفر",deliveredTitle:"تم توصيل طلبك",cancelledTitle:"تم إلغاء هذا الطلب",delayedTitle:"طلبك متأخر قليلًا",trackingTitle:"تتبعي طلبك",trackingBody:"تقدم المراجعة والتنفيذ",confirmationTitle:"تم استلام طلبك بنجاح",confirmationBody:"سنراجع المنتجات والسعر والتوفر، وسيتواصل معك فريقنا لتأكيد التفاصيل وطريقة الدفع.",confirmationPending:"الطلب ليس مؤكدًا نهائيًا حتى يتواصل معك فريق ÉLORA.",followRequest:"متابعة الطلب",backShopping:"العودة للتسوق",summary:"ملخص الطلب"},
    shein:{eyebrow:"طلب خاص من ÉLORA",title:"اطلبي القطعة التي أعجبتك من SHEIN",intro:"انسخي رابط المنتج، اختاري التفاصيل المطلوبة، وسنراجع السعر والتوفر قبل تأكيد الطلب.",finalPriceNote:"يتم تأكيد السعر النهائي بعد المراجعة فقط.",ctaTitle:"مش لاقية اللي بتدوري عليه؟",ctaBody:"اطلبيه من SHEIN وإحنا نوفّرهولك.",ctaButton:"اطلبي من SHEIN",howTitle:"كيف تعمل الخدمة؟",steps:["انسخي رابط المنتج من SHEIN.","أضيفي اللون والمقاس والكمية.","أرسلي الطلب للمراجعة.","نراجع السعر والتوفر.","نتواصل معك لتأكيد الطلب وطريقة الدفع."],formTitle:"تفاصيل طلب المنتج",productUrl:"رابط منتج SHEIN",urlPlaceholder:"الصقي رابط المنتج من SHEIN هنا",productName:"اسم المنتج",productNamePlaceholder:"اكتبي اسم المنتج يدويًا (اختياري)",optional:"اختياري",image:"صورة المنتج",upload:"ارفعي صورة أو Screenshot",uploadHint:"الصورة اختيارية لكنها تساعدنا في مراجعة الطلب. JPG أو PNG أو WebP.",previewAlt:"معاينة صورة المنتج المختارة",removeImage:"حذف الصورة",color:"اللون المطلوب",colorPlaceholder:"اكتبي اللون كما يظهر بالضبط",size:"المقاس المطلوب",chooseSize:"اختاري المقاس",sheinSizeText:"المقاس المكتوب على صفحة SHEIN",sheinSizePlaceholder:"وصف المقاس أو القياسات إن وُجدت",quantity:"الكمية",decreaseQuantity:"تقليل الكمية",increaseQuantity:"زيادة الكمية",displayedPrice:"السعر الظاهر على SHEIN",displayedPriceNote:"مرجع اختياري فقط، وليس السعر النهائي وقد يتغير.",displayedCurrency:"العملة الظاهرة",otherCurrency:"أخرى",notes:"ملاحظات إضافية",notesPlaceholder:"رابط لون معين أو القياسات أو أي تفاصيل مفيدة",consent:"أفهم أن السعر والتوفر وموعد الوصول سيتم تأكيدهم بعد مراجعة الطلب.",addToCart:"إضافة الطلب إلى السلة",updateCart:"تحديث الطلب",invalidUrl:"يرجى إدخال رابط صحيح لمنتج من SHEIN.",imageError:"يرجى اختيار صورة JPG أو PNG أو WebP.",imageTooLarge:"تعذر حفظ الصورة. اختاري صورة أصغر.",added:"تمت إضافة الطلب الخاص إلى حقيبتك",updated:"تم تحديث الطلب الخاص",specialBadge:"طلب خاص من SHEIN",fallbackName:"منتج من SHEIN",openLink:"فتح الرابط",pricePending:"السعر قيد المراجعة",availabilityPending:"التوفر قيد المراجعة",editRequest:"تعديل الطلب",pendingNotice:"سيتم تأكيد السعر والتوفر وموعد الوصول بعد المراجعة.",displayedPriceLabel:"السعر الذي أدخلته",finalPrice:"السعر النهائي",notSet:"لم يُحدد",availability:"التوفر",reviewStatus:"حالة المراجعة",detailsTitle:"تفاصيل طلب SHEIN",cancelSuccess:"تم إلغاء الطلب",cartEmptyCta:"يمكنك أيضًا طلب منتج من SHEIN.",demoSaved:"محفوظ محليًا على هذا الجهاز للتجربة."},
    returns:{title:"الاسترجاع والاستبدال",body:"خطوات بسيطة وتحديثات واضحة ودعم عند الحاجة.",start:"بدء طلب استرجاع",policy:"سياسة الاسترجاع",requestTitle:"طلب استرجاع",orderNumber:"رقم الطلب",reason:"سبب الاسترجاع",reasonPlaceholder:"اختاري السبب",fit:"المقاس غير مناسب",changed:"غيرت رأيي",damaged:"وصلت القطعة تالفة",other:"سبب آخر",details:"أخبرينا بالمزيد",upload:"ارفعي صورة",uploadHint:"PNG أو JPG حتى ١٠ ميجابايت",submittedTitle:"تم إرسال طلب الاسترجاع",submittedBody:"سنراجع طلبك ونرسل الخطوات التالية خلال يوم عمل.",emptyTitle:"لا توجد طلبات استرجاع",emptyBody:"ستظهر هنا طلبات الاسترجاع الحالية والسابقة.",acceptedTitle:"تم قبول الاسترجاع",acceptedBody:"اتبعي التعليمات المرسلة لبريدك لإعادة القطعة.",rejectedTitle:"لم تتم الموافقة على الاسترجاع",rejectedBody:"القطعة خارج فترة الاسترجاع. تواصلي مع الدعم للمساعدة.",refundTitle:"جارٍ رد المبلغ",refundBody:"نعالج المبلغ وسيظهر خلال ٥–٧ أيام عمل."},
    states:{loadingTitle:"نجهز اختياراتك",loadingBody:"بعض التفاصيل الجميلة أوشكت أن تصبح جاهزة.",emptyTitle:"لا يوجد شيء هنا بعد",emptyBody:"اكتشفي التشكيلة وابدئي اختياراتك.",offlineTitle:"يبدو أنكِ غير متصلة",offlineBody:"تحققي من اتصال الإنترنت وحاولي مجددًا. حقيبتك المحفوظة ما زالت متاحة.",notFoundTitle:"الصفحة غير موجودة",notFoundBody:"الصفحة التي تبحثين عنها نُقلت أو لم تعد موجودة.",successTitle:"كل شيء جاهز",successBody:"تم حفظ تغييراتك بنجاح.",errorTitle:"تعذر إكمال العملية",errorBody:"حاولي مرة أخرى بعد قليل."},
    footer:{story:"أزياء وحقائب وأحذية وإكسسوارات وجمال منتقاة لكل جانب منها.",shop:"تسوقي",help:"المساعدة",follow:"تابعينا",newIn:"وصل حديثًا",fashion:"أزياء",bagsShoes:"حقائب وأحذية",accessoriesBeauty:"إكسسوارات وجمال",requestShein:"اطلبي من SHEIN",delivery:"التوصيل",exchange:"سياسة الاستبدال",track:"تتبع الطلب",instagram:"إنستجرام",tiktok:"تيك توك",whatsapp:"واتساب",pinterest:"بنترست",rights:"© ٢٠٢٦ إيلورا. صُمم بعناية.",privacy:"الخصوصية • الشروط • الاسترجاع"}
  };

  window.ELORA_I18N.en.shein.oneSize = "One Size";
  window.ELORA_I18N.en.shein.customOther = "Custom / Other";
  window.ELORA_I18N.ar.shein.oneSize = "مقاس واحد";
  window.ELORA_I18N.ar.shein.customOther = "مقاس مخصص / آخر";
  window.ELORA_I18N.en.shop.browseDepartments = "Browse departments";
  window.ELORA_I18N.en.shop.allDepartments = "All Departments";
  window.ELORA_I18N.ar.shop.browseDepartments = "تصفحي الأقسام";
  window.ELORA_I18N.ar.shop.allDepartments = "كل الأقسام";
  window.ELORA_I18N.en.cart.miniTitle = "Bag Summary";
  window.ELORA_I18N.en.cart.viewFullCart = "View Full Bag";
  window.ELORA_I18N.en.cart.emptyMini = "Your bag is currently empty.";
  window.ELORA_I18N.en.cart.moreItems = "more items";
  window.ELORA_I18N.en.cart.specialRequest = "Special request";
  window.ELORA_I18N.en.cart.invalidPromo = "This promo code is not valid.";
  window.ELORA_I18N.en.cart.removed = "Item removed from your bag.";
  window.ELORA_I18N.en.cart.sizeUpdated = "Size updated.";
  window.ELORA_I18N.ar.cart.miniTitle = "ملخص الحقيبة";
  window.ELORA_I18N.ar.cart.viewFullCart = "عرض السلة كاملة";
  window.ELORA_I18N.ar.cart.emptyMini = "حقيبتك فارغة حاليًا.";
  window.ELORA_I18N.ar.cart.moreItems = "قطع إضافية";
  window.ELORA_I18N.ar.cart.specialRequest = "طلب خاص";
  window.ELORA_I18N.ar.cart.invalidPromo = "كود الخصم غير صحيح.";
  window.ELORA_I18N.ar.cart.removed = "تمت إزالة المنتج من السلة.";
  window.ELORA_I18N.ar.cart.sizeUpdated = "تم تحديث المقاس.";
  window.ELORA_I18N.en.chatbot = {
    name:"ÉLORA Concierge", tagline:"Your smart shopping assistant", automated:"Automated shopping assistant", ready:"Ready to help",
    open:"Open ÉLORA Concierge", close:"Close assistant", minimize:"Minimize assistant", back:"Back", newChat:"New conversation", clear:"Clear conversation",
    tooltip:"Need help?", placeholder:"Write your message…", send:"Send message", characterCount:"characters remaining", scrollLatest:"Scroll to latest message",
    typing:"ÉLORA Concierge is preparing a reply", security:"Do not share payment details or passwords in the chat.", automatedNotice:"This is an automated local shopping assistant, not a live team member.",
    starterChoose:"Help me choose", starterSearch:"Find a product", starterSize:"Find my size", starterTrack:"Track my order", starterShein:"Request from SHEIN", starterPolicies:"Shipping & returns", starterContact:"Contact the team",
    viewProduct:"View Product", addCart:"Add to Cart", wishlist:"Add to wishlist", removeWishlist:"Remove from wishlist", showMore:"Show more results", alternatives:"Show alternatives", requestShein:"Request from SHEIN",
    openTracking:"Open full tracking", openReturns:"Open Returns", openShein:"Open SHEIN Request", copySummary:"Copy conversation summary", continueWhatsApp:"Continue via WhatsApp", continueEmail:"Continue by email", copied:"Conversation summary copied", copyFailed:"Select and copy the summary below.",
    availableSizes:"Available sizes", availabilityReview:"Availability confirmed after review", selectSize:"Select size", currentPage:"Current page", messageSent:"Sent", localOnly:"Saved on this device only",
    typeFashion:"Clothing", typeBags:"Bags", typeShoes:"Shoes", typeAccessories:"Accessories", typeBeauty:"Beauty & care",
    occasionDaily:"Everyday", occasionWork:"Work", occasionUniversity:"University", occasionOuting:"Going out", occasionEvent:"Occasion", occasionGift:"Gift",
    budgetOpen:"Open budget", colorAny:"Any color", styleClassic:"Classic", styleCasual:"Casual", styleElegant:"Elegant", styleTrendy:"Trendy", styleMinimal:"Minimal",
    confirmNew:"Start a new conversation?", emptyMessage:"Write a message first.", tooLong:"Your message is too long.", sensitiveWarning:"For your safety, payment details, passwords, and verification codes are not stored or processed here.",
    statusPending:"Pending Review", nudgeClose:"Dismiss help suggestion", emailSubject:"ÉLORA contact request", customerLabel:"Customer", assistantLabel:"Assistant"
  };
  window.ELORA_I18N.ar.chatbot = {
    name:"مساعدة ÉLORA", tagline:"مساعدتك الذكية للتسوق", automated:"مساعد التسوق الآلي", ready:"جاهزة للمساعدة",
    open:"فتح مساعدة ÉLORA", close:"إغلاق المساعدة", minimize:"تصغير المساعدة", back:"رجوع", newChat:"محادثة جديدة", clear:"مسح المحادثة",
    tooltip:"تحتاجين مساعدة؟", placeholder:"اكتبي رسالتك…", send:"إرسال الرسالة", characterCount:"حرف متبقٍ", scrollLatest:"الانتقال لأحدث رسالة",
    typing:"مساعدة ÉLORA تجهز الرد", security:"لا تشاركي بيانات دفع أو كلمات مرور داخل المحادثة.", automatedNotice:"هذا مساعد تسوق آلي يعمل محليًا، وليس موظفة مباشرة من الفريق.",
    starterChoose:"ساعديني أختار", starterSearch:"ابحثي عن منتج", starterSize:"معرفة المقاس المناسب", starterTrack:"متابعة طلبي", starterShein:"اطلبي من SHEIN", starterPolicies:"الشحن والاسترجاع", starterContact:"التحدث مع الفريق",
    viewProduct:"عرض المنتج", addCart:"إضافة إلى السلة", wishlist:"إضافة إلى المفضلة", removeWishlist:"إزالة من المفضلة", showMore:"عرض نتائج أكثر", alternatives:"عرض بدائل", requestShein:"اطلبي من SHEIN",
    openTracking:"فتح صفحة التتبع", openReturns:"فتح صفحة الاسترجاع", openShein:"فتح خدمة SHEIN", copySummary:"نسخ ملخص المحادثة", continueWhatsApp:"متابعة عبر WhatsApp", continueEmail:"متابعة عبر البريد", copied:"تم نسخ ملخص المحادثة", copyFailed:"حددي الملخص التالي وانسخيه.",
    availableSizes:"المقاسات المتاحة", availabilityReview:"التوفر يُؤكد بعد المراجعة", selectSize:"اختاري المقاس", currentPage:"الصفحة الحالية", messageSent:"تم الإرسال", localOnly:"محفوظ على هذا الجهاز فقط",
    typeFashion:"ملابس", typeBags:"حقائب", typeShoes:"أحذية", typeAccessories:"إكسسوارات", typeBeauty:"جمال وعناية",
    occasionDaily:"يومي", occasionWork:"عمل", occasionUniversity:"جامعة", occasionOuting:"خروجة", occasionEvent:"مناسبة", occasionGift:"هدية",
    budgetOpen:"ميزانية مفتوحة", colorAny:"أي لون", styleClassic:"كلاسيك", styleCasual:"كاجوال", styleElegant:"أنيق", styleTrendy:"عصري", styleMinimal:"بسيط",
    confirmNew:"بدء محادثة جديدة؟", emptyMessage:"اكتبي رسالة أولًا.", tooLong:"الرسالة أطول من الحد المسموح.", sensitiveWarning:"لحمايتك، لا يتم حفظ أو معالجة بيانات الدفع أو كلمات المرور أو رموز التحقق هنا.",
    statusPending:"بانتظار المراجعة", nudgeClose:"إغلاق اقتراح المساعدة", emailSubject:"طلب تواصل مع ÉLORA", customerLabel:"العميلة", assistantLabel:"المساعد"
  };
  function get(obj, path) { return path.split(".").reduce(function (value, key) { return value && value[key]; }, obj); }
  window.ELORA.I18N = {
    language: "en",
    detect: function () {
      var saved = window.ELORA.store && window.ELORA.store.getLanguage ? window.ELORA.store.getLanguage() : null;
      if (saved === "ar" || saved === "en") return saved;
      var languages = navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language || "en"];
      return languages.some(function (lang) { return String(lang).toLowerCase().indexOf("ar") === 0; }) ? "ar" : "en";
    },
    t: function (path) { return get(window.ELORA_I18N[this.language], path) || get(window.ELORA_I18N.en, path) || path; },
    pick: function (value) { return value && value[this.language] !== undefined ? value[this.language] : value; },
    set: function (lang, persist) {
      this.language = lang === "ar" ? "ar" : "en";
      document.documentElement.lang = this.language;
      document.documentElement.dir = this.language === "ar" ? "rtl" : "ltr";
      document.title = this.t("meta.title");
      if (persist && window.ELORA.store && window.ELORA.store.setLanguage) window.ELORA.store.setLanguage(this.language);
      if (document.dispatchEvent && typeof CustomEvent === "function") document.dispatchEvent(new CustomEvent("elora:language", { detail: { language:this.language } }));
    },
    toggle: function () { this.set(this.language === "en" ? "ar" : "en", true); }
  };
})();
